// github.com/mikhail5545/proto-go
// shared proto module for vitainmove project microservices
// Copyright (C) 2025  Mikhail Kulik

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.

// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: training_session/v0/training_session.proto

package trainingsesssionpb

import (
	v0 "github.com/mikhail5545/proto-go/proto/product/v0"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrainingSession struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ProductId       string                 `protobuf:"bytes,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Product         *v0.Product            `protobuf:"bytes,5,opt,name=product,proto3" json:"product,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,6,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	Format          string                 `protobuf:"bytes,7,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TrainingSession) Reset() {
	*x = TrainingSession{}
	mi := &file_training_session_v0_training_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingSession) ProtoMessage() {}

func (x *TrainingSession) ProtoReflect() protoreflect.Message {
	mi := &file_training_session_v0_training_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingSession.ProtoReflect.Descriptor instead.
func (*TrainingSession) Descriptor() ([]byte, []int) {
	return file_training_session_v0_training_session_proto_rawDescGZIP(), []int{0}
}

func (x *TrainingSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TrainingSession) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TrainingSession) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *TrainingSession) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *TrainingSession) GetProduct() *v0.Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *TrainingSession) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *TrainingSession) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type TrainingSessionProductInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float32                `protobuf:"fixed32,1,opt,name=price,proto3" json:"price,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainingSessionProductInfo) Reset() {
	*x = TrainingSessionProductInfo{}
	mi := &file_training_session_v0_training_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingSessionProductInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingSessionProductInfo) ProtoMessage() {}

func (x *TrainingSessionProductInfo) ProtoReflect() protoreflect.Message {
	mi := &file_training_session_v0_training_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingSessionProductInfo.ProtoReflect.Descriptor instead.
func (*TrainingSessionProductInfo) Descriptor() ([]byte, []int) {
	return file_training_session_v0_training_session_proto_rawDescGZIP(), []int{1}
}

func (x *TrainingSessionProductInfo) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TrainingSessionProductInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrainingSessionProductInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TrainingSessionProductInfo) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type GetTrainingSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrainingSessionRequest) Reset() {
	*x = GetTrainingSessionRequest{}
	mi := &file_training_session_v0_training_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrainingSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrainingSessionRequest) ProtoMessage() {}

func (x *GetTrainingSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_training_session_v0_training_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrainingSessionRequest.ProtoReflect.Descriptor instead.
func (*GetTrainingSessionRequest) Descriptor() ([]byte, []int) {
	return file_training_session_v0_training_session_proto_rawDescGZIP(), []int{2}
}

func (x *GetTrainingSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTrainingSessionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TrainingSession *TrainingSession       `protobuf:"bytes,1,opt,name=training_session,json=trainingSession,proto3" json:"training_session,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetTrainingSessionResponse) Reset() {
	*x = GetTrainingSessionResponse{}
	mi := &file_training_session_v0_training_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrainingSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrainingSessionResponse) ProtoMessage() {}

func (x *GetTrainingSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_training_session_v0_training_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrainingSessionResponse.ProtoReflect.Descriptor instead.
func (*GetTrainingSessionResponse) Descriptor() ([]byte, []int) {
	return file_training_session_v0_training_session_proto_rawDescGZIP(), []int{3}
}

func (x *GetTrainingSessionResponse) GetTrainingSession() *TrainingSession {
	if x != nil {
		return x.TrainingSession
	}
	return nil
}

type ListTrainingSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrainingSessionsRequest) Reset() {
	*x = ListTrainingSessionsRequest{}
	mi := &file_training_session_v0_training_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrainingSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrainingSessionsRequest) ProtoMessage() {}

func (x *ListTrainingSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_training_session_v0_training_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrainingSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListTrainingSessionsRequest) Descriptor() ([]byte, []int) {
	return file_training_session_v0_training_session_proto_rawDescGZIP(), []int{4}
}

func (x *ListTrainingSessionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTrainingSessionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListTrainingSessionsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TrainingSessions []*TrainingSession     `protobuf:"bytes,1,rep,name=training_sessions,json=trainingSessions,proto3" json:"training_sessions,omitempty"`
	Total            int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListTrainingSessionsResponse) Reset() {
	*x = ListTrainingSessionsResponse{}
	mi := &file_training_session_v0_training_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrainingSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrainingSessionsResponse) ProtoMessage() {}

func (x *ListTrainingSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_training_session_v0_training_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrainingSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListTrainingSessionsResponse) Descriptor() ([]byte, []int) {
	return file_training_session_v0_training_session_proto_rawDescGZIP(), []int{5}
}

func (x *ListTrainingSessionsResponse) GetTrainingSessions() []*TrainingSession {
	if x != nil {
		return x.TrainingSessions
	}
	return nil
}

func (x *ListTrainingSessionsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateTrainingSessionRequest struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	DurationMinutes int32                       `protobuf:"varint,1,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	Format          string                      `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	ProductInfo     *TrainingSessionProductInfo `protobuf:"bytes,3,opt,name=product_info,json=productInfo,proto3" json:"product_info,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTrainingSessionRequest) Reset() {
	*x = CreateTrainingSessionRequest{}
	mi := &file_training_session_v0_training_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTrainingSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrainingSessionRequest) ProtoMessage() {}

func (x *CreateTrainingSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_training_session_v0_training_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrainingSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateTrainingSessionRequest) Descriptor() ([]byte, []int) {
	return file_training_session_v0_training_session_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTrainingSessionRequest) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *CreateTrainingSessionRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *CreateTrainingSessionRequest) GetProductInfo() *TrainingSessionProductInfo {
	if x != nil {
		return x.ProductInfo
	}
	return nil
}

type CreateTrainingSessionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TrainingSession *TrainingSession       `protobuf:"bytes,1,opt,name=training_session,json=trainingSession,proto3" json:"training_session,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTrainingSessionResponse) Reset() {
	*x = CreateTrainingSessionResponse{}
	mi := &file_training_session_v0_training_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTrainingSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrainingSessionResponse) ProtoMessage() {}

func (x *CreateTrainingSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_training_session_v0_training_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrainingSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateTrainingSessionResponse) Descriptor() ([]byte, []int) {
	return file_training_session_v0_training_session_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTrainingSessionResponse) GetTrainingSession() *TrainingSession {
	if x != nil {
		return x.TrainingSession
	}
	return nil
}

type UpdateTrainingSessionRequest struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	Id              string                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DurationMinutes *int32                      `protobuf:"varint,2,opt,name=duration_minutes,json=durationMinutes,proto3,oneof" json:"duration_minutes,omitempty"`
	Format          *string                     `protobuf:"bytes,3,opt,name=format,proto3,oneof" json:"format,omitempty"`
	ProductInfo     *TrainingSessionProductInfo `protobuf:"bytes,4,opt,name=product_info,json=productInfo,proto3,oneof" json:"product_info,omitempty"`
	UpdateMask      *fieldmaskpb.FieldMask      `protobuf:"bytes,5,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateTrainingSessionRequest) Reset() {
	*x = UpdateTrainingSessionRequest{}
	mi := &file_training_session_v0_training_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTrainingSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTrainingSessionRequest) ProtoMessage() {}

func (x *UpdateTrainingSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_training_session_v0_training_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTrainingSessionRequest.ProtoReflect.Descriptor instead.
func (*UpdateTrainingSessionRequest) Descriptor() ([]byte, []int) {
	return file_training_session_v0_training_session_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTrainingSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTrainingSessionRequest) GetDurationMinutes() int32 {
	if x != nil && x.DurationMinutes != nil {
		return *x.DurationMinutes
	}
	return 0
}

func (x *UpdateTrainingSessionRequest) GetFormat() string {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return ""
}

func (x *UpdateTrainingSessionRequest) GetProductInfo() *TrainingSessionProductInfo {
	if x != nil {
		return x.ProductInfo
	}
	return nil
}

func (x *UpdateTrainingSessionRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateTrainingSessionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TrainingSession *TrainingSession       `protobuf:"bytes,1,opt,name=training_session,json=trainingSession,proto3" json:"training_session,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateTrainingSessionResponse) Reset() {
	*x = UpdateTrainingSessionResponse{}
	mi := &file_training_session_v0_training_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTrainingSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTrainingSessionResponse) ProtoMessage() {}

func (x *UpdateTrainingSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_training_session_v0_training_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTrainingSessionResponse.ProtoReflect.Descriptor instead.
func (*UpdateTrainingSessionResponse) Descriptor() ([]byte, []int) {
	return file_training_session_v0_training_session_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTrainingSessionResponse) GetTrainingSession() *TrainingSession {
	if x != nil {
		return x.TrainingSession
	}
	return nil
}

type DeleteTrainingSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTrainingSessionRequest) Reset() {
	*x = DeleteTrainingSessionRequest{}
	mi := &file_training_session_v0_training_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTrainingSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTrainingSessionRequest) ProtoMessage() {}

func (x *DeleteTrainingSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_training_session_v0_training_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTrainingSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteTrainingSessionRequest) Descriptor() ([]byte, []int) {
	return file_training_session_v0_training_session_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTrainingSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTrainingSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTrainingSessionResponse) Reset() {
	*x = DeleteTrainingSessionResponse{}
	mi := &file_training_session_v0_training_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTrainingSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTrainingSessionResponse) ProtoMessage() {}

func (x *DeleteTrainingSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_training_session_v0_training_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTrainingSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteTrainingSessionResponse) Descriptor() ([]byte, []int) {
	return file_training_session_v0_training_session_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteTrainingSessionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_training_session_v0_training_session_proto protoreflect.FileDescriptor

const file_training_session_v0_training_session_proto_rawDesc = "" +
	"\n" +
	"*training_session/v0/training_session.proto\x12\x13training_session.v0\x1a\x18product/v0/product.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\"\xa8\x02\n" +
	"\x0fTrainingSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\tR\tproductId\x12-\n" +
	"\aproduct\x18\x05 \x01(\v2\x13.product.v0.ProductR\aproduct\x12)\n" +
	"\x10duration_minutes\x18\x06 \x01(\x05R\x0fdurationMinutes\x12\x16\n" +
	"\x06format\x18\a \x01(\tR\x06format\"\x85\x01\n" +
	"\x1aTrainingSessionProductInfo\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x02R\x05price\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\"+\n" +
	"\x19GetTrainingSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"m\n" +
	"\x1aGetTrainingSessionResponse\x12O\n" +
	"\x10training_session\x18\x01 \x01(\v2$.training_session.v0.TrainingSessionR\x0ftrainingSession\"K\n" +
	"\x1bListTrainingSessionsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\x87\x01\n" +
	"\x1cListTrainingSessionsResponse\x12Q\n" +
	"\x11training_sessions\x18\x01 \x03(\v2$.training_session.v0.TrainingSessionR\x10trainingSessions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xb5\x01\n" +
	"\x1cCreateTrainingSessionRequest\x12)\n" +
	"\x10duration_minutes\x18\x01 \x01(\x05R\x0fdurationMinutes\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12R\n" +
	"\fproduct_info\x18\x03 \x01(\v2/.training_session.v0.TrainingSessionProductInfoR\vproductInfo\"p\n" +
	"\x1dCreateTrainingSessionResponse\x12O\n" +
	"\x10training_session\x18\x01 \x01(\v2$.training_session.v0.TrainingSessionR\x0ftrainingSession\"\xc2\x02\n" +
	"\x1cUpdateTrainingSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x10duration_minutes\x18\x02 \x01(\x05H\x00R\x0fdurationMinutes\x88\x01\x01\x12\x1b\n" +
	"\x06format\x18\x03 \x01(\tH\x01R\x06format\x88\x01\x01\x12W\n" +
	"\fproduct_info\x18\x04 \x01(\v2/.training_session.v0.TrainingSessionProductInfoH\x02R\vproductInfo\x88\x01\x01\x12;\n" +
	"\vupdate_mask\x18\x05 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMaskB\x13\n" +
	"\x11_duration_minutesB\t\n" +
	"\a_formatB\x0f\n" +
	"\r_product_info\"p\n" +
	"\x1dUpdateTrainingSessionResponse\x12O\n" +
	"\x10training_session\x18\x01 \x01(\v2$.training_session.v0.TrainingSessionR\x0ftrainingSession\".\n" +
	"\x1cDeleteTrainingSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x1dDeleteTrainingSessionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\x99\x05\n" +
	"\x16TrainingSessionService\x12w\n" +
	"\x12GetTrainingSession\x12..training_session.v0.GetTrainingSessionRequest\x1a/.training_session.v0.GetTrainingSessionResponse\"\x00\x12}\n" +
	"\x14ListTrainingSessions\x120.training_session.v0.ListTrainingSessionsRequest\x1a1.training_session.v0.ListTrainingSessionsResponse\"\x00\x12\x80\x01\n" +
	"\x15CreateTrainingSession\x121.training_session.v0.CreateTrainingSessionRequest\x1a2.training_session.v0.CreateTrainingSessionResponse\"\x00\x12\x80\x01\n" +
	"\x15UpdateTrainingSession\x121.training_session.v0.UpdateTrainingSessionRequest\x1a2.training_session.v0.UpdateTrainingSessionResponse\"\x00\x12\x80\x01\n" +
	"\x15DeleteTrainingSession\x121.training_session.v0.DeleteTrainingSessionRequest\x1a2.training_session.v0.DeleteTrainingSessionResponse\"\x00BNZLgithub.com/mikhail5545/proto-go/proto/training_session/v0;trainingsesssionpbb\x06proto3"

var (
	file_training_session_v0_training_session_proto_rawDescOnce sync.Once
	file_training_session_v0_training_session_proto_rawDescData []byte
)

func file_training_session_v0_training_session_proto_rawDescGZIP() []byte {
	file_training_session_v0_training_session_proto_rawDescOnce.Do(func() {
		file_training_session_v0_training_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_training_session_v0_training_session_proto_rawDesc), len(file_training_session_v0_training_session_proto_rawDesc)))
	})
	return file_training_session_v0_training_session_proto_rawDescData
}

var file_training_session_v0_training_session_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_training_session_v0_training_session_proto_goTypes = []any{
	(*TrainingSession)(nil),               // 0: training_session.v0.TrainingSession
	(*TrainingSessionProductInfo)(nil),    // 1: training_session.v0.TrainingSessionProductInfo
	(*GetTrainingSessionRequest)(nil),     // 2: training_session.v0.GetTrainingSessionRequest
	(*GetTrainingSessionResponse)(nil),    // 3: training_session.v0.GetTrainingSessionResponse
	(*ListTrainingSessionsRequest)(nil),   // 4: training_session.v0.ListTrainingSessionsRequest
	(*ListTrainingSessionsResponse)(nil),  // 5: training_session.v0.ListTrainingSessionsResponse
	(*CreateTrainingSessionRequest)(nil),  // 6: training_session.v0.CreateTrainingSessionRequest
	(*CreateTrainingSessionResponse)(nil), // 7: training_session.v0.CreateTrainingSessionResponse
	(*UpdateTrainingSessionRequest)(nil),  // 8: training_session.v0.UpdateTrainingSessionRequest
	(*UpdateTrainingSessionResponse)(nil), // 9: training_session.v0.UpdateTrainingSessionResponse
	(*DeleteTrainingSessionRequest)(nil),  // 10: training_session.v0.DeleteTrainingSessionRequest
	(*DeleteTrainingSessionResponse)(nil), // 11: training_session.v0.DeleteTrainingSessionResponse
	(*timestamppb.Timestamp)(nil),         // 12: google.protobuf.Timestamp
	(*v0.Product)(nil),                    // 13: product.v0.Product
	(*fieldmaskpb.FieldMask)(nil),         // 14: google.protobuf.FieldMask
}
var file_training_session_v0_training_session_proto_depIdxs = []int32{
	12, // 0: training_session.v0.TrainingSession.created_at:type_name -> google.protobuf.Timestamp
	12, // 1: training_session.v0.TrainingSession.updated_at:type_name -> google.protobuf.Timestamp
	13, // 2: training_session.v0.TrainingSession.product:type_name -> product.v0.Product
	0,  // 3: training_session.v0.GetTrainingSessionResponse.training_session:type_name -> training_session.v0.TrainingSession
	0,  // 4: training_session.v0.ListTrainingSessionsResponse.training_sessions:type_name -> training_session.v0.TrainingSession
	1,  // 5: training_session.v0.CreateTrainingSessionRequest.product_info:type_name -> training_session.v0.TrainingSessionProductInfo
	0,  // 6: training_session.v0.CreateTrainingSessionResponse.training_session:type_name -> training_session.v0.TrainingSession
	1,  // 7: training_session.v0.UpdateTrainingSessionRequest.product_info:type_name -> training_session.v0.TrainingSessionProductInfo
	14, // 8: training_session.v0.UpdateTrainingSessionRequest.update_mask:type_name -> google.protobuf.FieldMask
	0,  // 9: training_session.v0.UpdateTrainingSessionResponse.training_session:type_name -> training_session.v0.TrainingSession
	2,  // 10: training_session.v0.TrainingSessionService.GetTrainingSession:input_type -> training_session.v0.GetTrainingSessionRequest
	4,  // 11: training_session.v0.TrainingSessionService.ListTrainingSessions:input_type -> training_session.v0.ListTrainingSessionsRequest
	6,  // 12: training_session.v0.TrainingSessionService.CreateTrainingSession:input_type -> training_session.v0.CreateTrainingSessionRequest
	8,  // 13: training_session.v0.TrainingSessionService.UpdateTrainingSession:input_type -> training_session.v0.UpdateTrainingSessionRequest
	10, // 14: training_session.v0.TrainingSessionService.DeleteTrainingSession:input_type -> training_session.v0.DeleteTrainingSessionRequest
	3,  // 15: training_session.v0.TrainingSessionService.GetTrainingSession:output_type -> training_session.v0.GetTrainingSessionResponse
	5,  // 16: training_session.v0.TrainingSessionService.ListTrainingSessions:output_type -> training_session.v0.ListTrainingSessionsResponse
	7,  // 17: training_session.v0.TrainingSessionService.CreateTrainingSession:output_type -> training_session.v0.CreateTrainingSessionResponse
	9,  // 18: training_session.v0.TrainingSessionService.UpdateTrainingSession:output_type -> training_session.v0.UpdateTrainingSessionResponse
	11, // 19: training_session.v0.TrainingSessionService.DeleteTrainingSession:output_type -> training_session.v0.DeleteTrainingSessionResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_training_session_v0_training_session_proto_init() }
func file_training_session_v0_training_session_proto_init() {
	if File_training_session_v0_training_session_proto != nil {
		return
	}
	file_training_session_v0_training_session_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_training_session_v0_training_session_proto_rawDesc), len(file_training_session_v0_training_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_training_session_v0_training_session_proto_goTypes,
		DependencyIndexes: file_training_session_v0_training_session_proto_depIdxs,
		MessageInfos:      file_training_session_v0_training_session_proto_msgTypes,
	}.Build()
	File_training_session_v0_training_session_proto = out.File
	file_training_session_v0_training_session_proto_goTypes = nil
	file_training_session_v0_training_session_proto_depIdxs = nil
}
