// github.com/mikhail5545/proto-go
// shared proto module for vitainmove project microservices
// Copyright (C) 2025  Mikhail Kulik

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.

// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: user/v0/user.proto

package userpb

import (
	v0 "github.com/mikhail5545/proto-go/proto/address/v0"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Gender        *string                `protobuf:"bytes,7,opt,name=gender,proto3,oneof" json:"gender,omitempty"`
	DateOfBirth   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=date_of_birth,json=dateOfBirth,proto3,oneof" json:"date_of_birth,omitempty"`
	Email         string                 `protobuf:"bytes,9,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   *string                `protobuf:"bytes,10,opt,name=phone_number,json=phoneNumber,proto3,oneof" json:"phone_number,omitempty"`
	Country       *string                `protobuf:"bytes,11,opt,name=country,proto3,oneof" json:"country,omitempty"`
	IsVerified    bool                   `protobuf:"varint,12,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,13,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	Addresses     []*v0.Address          `protobuf:"bytes,14,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_v0_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_v0_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_v0_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetGender() string {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return ""
}

func (x *User) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhoneNumber() string {
	if x != nil && x.PhoneNumber != nil {
		return *x.PhoneNumber
	}
	return ""
}

func (x *User) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *User) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *User) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *User) GetAddresses() []*v0.Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type UserListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,9,opt,name=email,proto3" json:"email,omitempty"`
	IsVerified    bool                   `protobuf:"varint,12,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,13,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListItem) Reset() {
	*x = UserListItem{}
	mi := &file_user_v0_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListItem) ProtoMessage() {}

func (x *UserListItem) ProtoReflect() protoreflect.Message {
	mi := &file_user_v0_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListItem.ProtoReflect.Descriptor instead.
func (*UserListItem) Descriptor() ([]byte, []int) {
	return file_user_v0_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserListItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserListItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserListItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UserListItem) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserListItem) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserListItem) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserListItem) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *UserListItem) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_user_v0_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v0_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_user_v0_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_user_v0_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v0_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_user_v0_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByEmailRequest) Reset() {
	*x = GetByEmailRequest{}
	mi := &file_user_v0_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByEmailRequest) ProtoMessage() {}

func (x *GetByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v0_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByEmailRequest.ProtoReflect.Descriptor instead.
func (*GetByEmailRequest) Descriptor() ([]byte, []int) {
	return file_user_v0_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetByEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByEmailResponse) Reset() {
	*x = GetByEmailResponse{}
	mi := &file_user_v0_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByEmailResponse) ProtoMessage() {}

func (x *GetByEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v0_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByEmailResponse.ProtoReflect.Descriptor instead.
func (*GetByEmailResponse) Descriptor() ([]byte, []int) {
	return file_user_v0_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetByEmailResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetReducedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReducedRequest) Reset() {
	*x = GetReducedRequest{}
	mi := &file_user_v0_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReducedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReducedRequest) ProtoMessage() {}

func (x *GetReducedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v0_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReducedRequest.ProtoReflect.Descriptor instead.
func (*GetReducedRequest) Descriptor() ([]byte, []int) {
	return file_user_v0_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetReducedRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetReducedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserListItem          `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReducedResponse) Reset() {
	*x = GetReducedResponse{}
	mi := &file_user_v0_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReducedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReducedResponse) ProtoMessage() {}

func (x *GetReducedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v0_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReducedResponse.ProtoReflect.Descriptor instead.
func (*GetReducedResponse) Descriptor() ([]byte, []int) {
	return file_user_v0_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetReducedResponse) GetUser() *UserListItem {
	if x != nil {
		return x.User
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_user_v0_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v0_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_user_v0_user_proto_rawDescGZIP(), []int{8}
}

func (x *ListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserListItem        `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_user_v0_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v0_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_user_v0_user_proto_rawDescGZIP(), []int{9}
}

func (x *ListResponse) GetUsers() []*UserListItem {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	IsVerified    bool                   `protobuf:"varint,5,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_user_v0_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v0_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_user_v0_user_proto_rawDescGZIP(), []int{10}
}

func (x *CreateRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *CreateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateRequest) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	IsVerified    bool                   `protobuf:"varint,5,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_user_v0_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v0_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_user_v0_user_proto_rawDescGZIP(), []int{11}
}

func (x *CreateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateResponse) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *CreateResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     *string                `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	Gender        *string                `protobuf:"bytes,4,opt,name=gender,proto3,oneof" json:"gender,omitempty"`
	DateOfBirth   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=date_of_birth,json=dateOfBirth,proto3,oneof" json:"date_of_birth,omitempty"`
	Email         *string                `protobuf:"bytes,6,opt,name=email,proto3,oneof" json:"email,omitempty"`
	PhoneNumber   *string                `protobuf:"bytes,7,opt,name=phone_number,json=phoneNumber,proto3,oneof" json:"phone_number,omitempty"`
	Country       *string                `protobuf:"bytes,8,opt,name=country,proto3,oneof" json:"country,omitempty"`
	IsVerified    *bool                  `protobuf:"varint,9,opt,name=is_verified,json=isVerified,proto3,oneof" json:"is_verified,omitempty"`
	IsAdmin       *bool                  `protobuf:"varint,10,opt,name=is_admin,json=isAdmin,proto3,oneof" json:"is_admin,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,11,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_user_v0_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v0_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_user_v0_user_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRequest) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *UpdateRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *UpdateRequest) GetGender() string {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return ""
}

func (x *UpdateRequest) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *UpdateRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UpdateRequest) GetPhoneNumber() string {
	if x != nil && x.PhoneNumber != nil {
		return *x.PhoneNumber
	}
	return ""
}

func (x *UpdateRequest) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *UpdateRequest) GetIsVerified() bool {
	if x != nil && x.IsVerified != nil {
		return *x.IsVerified
	}
	return false
}

func (x *UpdateRequest) GetIsAdmin() bool {
	if x != nil && x.IsAdmin != nil {
		return *x.IsAdmin
	}
	return false
}

func (x *UpdateRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     *string                `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	Gender        *string                `protobuf:"bytes,4,opt,name=gender,proto3,oneof" json:"gender,omitempty"`
	DateOfBirth   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=date_of_birth,json=dateOfBirth,proto3,oneof" json:"date_of_birth,omitempty"`
	Email         *string                `protobuf:"bytes,6,opt,name=email,proto3,oneof" json:"email,omitempty"`
	PhoneNumber   *string                `protobuf:"bytes,7,opt,name=phone_number,json=phoneNumber,proto3,oneof" json:"phone_number,omitempty"`
	Country       *string                `protobuf:"bytes,8,opt,name=country,proto3,oneof" json:"country,omitempty"`
	IsVerified    *bool                  `protobuf:"varint,9,opt,name=is_verified,json=isVerified,proto3,oneof" json:"is_verified,omitempty"`
	IsAdmin       *bool                  `protobuf:"varint,10,opt,name=is_admin,json=isAdmin,proto3,oneof" json:"is_admin,omitempty"`
	Updated       *fieldmaskpb.FieldMask `protobuf:"bytes,11,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_user_v0_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v0_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_user_v0_user_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateResponse) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *UpdateResponse) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *UpdateResponse) GetGender() string {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return ""
}

func (x *UpdateResponse) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *UpdateResponse) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UpdateResponse) GetPhoneNumber() string {
	if x != nil && x.PhoneNumber != nil {
		return *x.PhoneNumber
	}
	return ""
}

func (x *UpdateResponse) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *UpdateResponse) GetIsVerified() bool {
	if x != nil && x.IsVerified != nil {
		return *x.IsVerified
	}
	return false
}

func (x *UpdateResponse) GetIsAdmin() bool {
	if x != nil && x.IsAdmin != nil {
		return *x.IsAdmin
	}
	return false
}

func (x *UpdateResponse) GetUpdated() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Updated
	}
	return nil
}

type SetVerificationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsVerified    bool                   `protobuf:"varint,2,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVerificationStatusRequest) Reset() {
	*x = SetVerificationStatusRequest{}
	mi := &file_user_v0_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVerificationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVerificationStatusRequest) ProtoMessage() {}

func (x *SetVerificationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v0_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVerificationStatusRequest.ProtoReflect.Descriptor instead.
func (*SetVerificationStatusRequest) Descriptor() ([]byte, []int) {
	return file_user_v0_user_proto_rawDescGZIP(), []int{14}
}

func (x *SetVerificationStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetVerificationStatusRequest) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

type SetVerificationStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsVerified    bool                   `protobuf:"varint,2,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVerificationStatusResponse) Reset() {
	*x = SetVerificationStatusResponse{}
	mi := &file_user_v0_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVerificationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVerificationStatusResponse) ProtoMessage() {}

func (x *SetVerificationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v0_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVerificationStatusResponse.ProtoReflect.Descriptor instead.
func (*SetVerificationStatusResponse) Descriptor() ([]byte, []int) {
	return file_user_v0_user_proto_rawDescGZIP(), []int{15}
}

func (x *SetVerificationStatusResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetVerificationStatusResponse) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

type SetRoleClaimRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,2,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRoleClaimRequest) Reset() {
	*x = SetRoleClaimRequest{}
	mi := &file_user_v0_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRoleClaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRoleClaimRequest) ProtoMessage() {}

func (x *SetRoleClaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v0_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRoleClaimRequest.ProtoReflect.Descriptor instead.
func (*SetRoleClaimRequest) Descriptor() ([]byte, []int) {
	return file_user_v0_user_proto_rawDescGZIP(), []int{16}
}

func (x *SetRoleClaimRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetRoleClaimRequest) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type SetRoleClaimResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,2,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRoleClaimResponse) Reset() {
	*x = SetRoleClaimResponse{}
	mi := &file_user_v0_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRoleClaimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRoleClaimResponse) ProtoMessage() {}

func (x *SetRoleClaimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v0_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRoleClaimResponse.ProtoReflect.Descriptor instead.
func (*SetRoleClaimResponse) Descriptor() ([]byte, []int) {
	return file_user_v0_user_proto_rawDescGZIP(), []int{17}
}

func (x *SetRoleClaimResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetRoleClaimResponse) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_user_v0_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v0_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_user_v0_user_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_user_v0_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v0_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_user_v0_user_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_user_v0_user_proto protoreflect.FileDescriptor

const file_user_v0_user_proto_rawDesc = "" +
	"\n" +
	"\x12user/v0/user.proto\x12\auser.v0\x1a\x18address/v0/address.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\"\xb0\x04\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\x1b\n" +
	"\x06gender\x18\a \x01(\tH\x00R\x06gender\x88\x01\x01\x12C\n" +
	"\rdate_of_birth\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x01R\vdateOfBirth\x88\x01\x01\x12\x14\n" +
	"\x05email\x18\t \x01(\tR\x05email\x12&\n" +
	"\fphone_number\x18\n" +
	" \x01(\tH\x02R\vphoneNumber\x88\x01\x01\x12\x1d\n" +
	"\acountry\x18\v \x01(\tH\x03R\acountry\x88\x01\x01\x12\x1f\n" +
	"\vis_verified\x18\f \x01(\bR\n" +
	"isVerified\x12\x19\n" +
	"\bis_admin\x18\r \x01(\bR\aisAdmin\x121\n" +
	"\taddresses\x18\x0e \x03(\v2\x13.address.v0.AddressR\taddressesB\t\n" +
	"\a_genderB\x10\n" +
	"\x0e_date_of_birthB\x0f\n" +
	"\r_phone_numberB\n" +
	"\n" +
	"\b_country\"\xa2\x02\n" +
	"\fUserListItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\t \x01(\tR\x05email\x12\x1f\n" +
	"\vis_verified\x18\f \x01(\bR\n" +
	"isVerified\x12\x19\n" +
	"\bis_admin\x18\r \x01(\bR\aisAdmin\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\vGetResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v0.UserR\x04user\")\n" +
	"\x11GetByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"7\n" +
	"\x12GetByEmailResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v0.UserR\x04user\"#\n" +
	"\x11GetReducedRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x12GetReducedResponse\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.user.v0.UserListItemR\x04user\";\n" +
	"\vListRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"Q\n" +
	"\fListResponse\x12+\n" +
	"\x05users\x18\x01 \x03(\v2\x15.user.v0.UserListItemR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xa3\x01\n" +
	"\rCreateRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x1f\n" +
	"\vis_verified\x18\x05 \x01(\bR\n" +
	"isVerified\"\xce\x01\n" +
	"\x0eCreateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1f\n" +
	"\vis_verified\x18\x05 \x01(\bR\n" +
	"isVerified\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xaa\x04\n" +
	"\rUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tH\x00R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x03 \x01(\tH\x01R\blastName\x88\x01\x01\x12\x1b\n" +
	"\x06gender\x18\x04 \x01(\tH\x02R\x06gender\x88\x01\x01\x12C\n" +
	"\rdate_of_birth\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\vdateOfBirth\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x06 \x01(\tH\x04R\x05email\x88\x01\x01\x12&\n" +
	"\fphone_number\x18\a \x01(\tH\x05R\vphoneNumber\x88\x01\x01\x12\x1d\n" +
	"\acountry\x18\b \x01(\tH\x06R\acountry\x88\x01\x01\x12$\n" +
	"\vis_verified\x18\t \x01(\bH\aR\n" +
	"isVerified\x88\x01\x01\x12\x1e\n" +
	"\bis_admin\x18\n" +
	" \x01(\bH\bR\aisAdmin\x88\x01\x01\x12;\n" +
	"\vupdate_mask\x18\v \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMaskB\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_nameB\t\n" +
	"\a_genderB\x10\n" +
	"\x0e_date_of_birthB\b\n" +
	"\x06_emailB\x0f\n" +
	"\r_phone_numberB\n" +
	"\n" +
	"\b_countryB\x0e\n" +
	"\f_is_verifiedB\v\n" +
	"\t_is_admin\"\xa4\x04\n" +
	"\x0eUpdateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tH\x00R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x03 \x01(\tH\x01R\blastName\x88\x01\x01\x12\x1b\n" +
	"\x06gender\x18\x04 \x01(\tH\x02R\x06gender\x88\x01\x01\x12C\n" +
	"\rdate_of_birth\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\vdateOfBirth\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x06 \x01(\tH\x04R\x05email\x88\x01\x01\x12&\n" +
	"\fphone_number\x18\a \x01(\tH\x05R\vphoneNumber\x88\x01\x01\x12\x1d\n" +
	"\acountry\x18\b \x01(\tH\x06R\acountry\x88\x01\x01\x12$\n" +
	"\vis_verified\x18\t \x01(\bH\aR\n" +
	"isVerified\x88\x01\x01\x12\x1e\n" +
	"\bis_admin\x18\n" +
	" \x01(\bH\bR\aisAdmin\x88\x01\x01\x124\n" +
	"\aupdated\x18\v \x01(\v2\x1a.google.protobuf.FieldMaskR\aupdatedB\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_nameB\t\n" +
	"\a_genderB\x10\n" +
	"\x0e_date_of_birthB\b\n" +
	"\x06_emailB\x0f\n" +
	"\r_phone_numberB\n" +
	"\n" +
	"\b_countryB\x0e\n" +
	"\f_is_verifiedB\v\n" +
	"\t_is_admin\"O\n" +
	"\x1cSetVerificationStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vis_verified\x18\x02 \x01(\bR\n" +
	"isVerified\"P\n" +
	"\x1dSetVerificationStatusResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vis_verified\x18\x02 \x01(\bR\n" +
	"isVerified\"@\n" +
	"\x13SetRoleClaimRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bis_admin\x18\x02 \x01(\bR\aisAdmin\"A\n" +
	"\x14SetRoleClaimResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bis_admin\x18\x02 \x01(\bR\aisAdmin\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\" \n" +
	"\x0eDeleteResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xb1\x04\n" +
	"\vUserService\x122\n" +
	"\x03Get\x12\x13.user.v0.GetRequest\x1a\x14.user.v0.GetResponse\"\x00\x12G\n" +
	"\n" +
	"GetReduced\x12\x1a.user.v0.GetReducedRequest\x1a\x1b.user.v0.GetReducedResponse\"\x00\x125\n" +
	"\x04List\x12\x14.user.v0.ListRequest\x1a\x15.user.v0.ListResponse\"\x00\x12;\n" +
	"\x06Create\x12\x16.user.v0.CreateRequest\x1a\x17.user.v0.CreateResponse\"\x00\x12h\n" +
	"\x15SetVerificationStatus\x12%.user.v0.SetVerificationStatusRequest\x1a&.user.v0.SetVerificationStatusResponse\"\x00\x12M\n" +
	"\fSetRoleClaim\x12\x1c.user.v0.SetRoleClaimRequest\x1a\x1d.user.v0.SetRoleClaimResponse\"\x00\x12;\n" +
	"\x06Update\x12\x16.user.v0.UpdateRequest\x1a\x17.user.v0.UpdateResponse\"\x00\x12;\n" +
	"\x06Delete\x12\x16.user.v0.DeleteRequest\x1a\x17.user.v0.DeleteResponse\"\x00B6Z4github.com/mikhail5545/proto-go/proto/user/v0;userpbb\x06proto3"

var (
	file_user_v0_user_proto_rawDescOnce sync.Once
	file_user_v0_user_proto_rawDescData []byte
)

func file_user_v0_user_proto_rawDescGZIP() []byte {
	file_user_v0_user_proto_rawDescOnce.Do(func() {
		file_user_v0_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v0_user_proto_rawDesc), len(file_user_v0_user_proto_rawDesc)))
	})
	return file_user_v0_user_proto_rawDescData
}

var file_user_v0_user_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_user_v0_user_proto_goTypes = []any{
	(*User)(nil),                          // 0: user.v0.User
	(*UserListItem)(nil),                  // 1: user.v0.UserListItem
	(*GetRequest)(nil),                    // 2: user.v0.GetRequest
	(*GetResponse)(nil),                   // 3: user.v0.GetResponse
	(*GetByEmailRequest)(nil),             // 4: user.v0.GetByEmailRequest
	(*GetByEmailResponse)(nil),            // 5: user.v0.GetByEmailResponse
	(*GetReducedRequest)(nil),             // 6: user.v0.GetReducedRequest
	(*GetReducedResponse)(nil),            // 7: user.v0.GetReducedResponse
	(*ListRequest)(nil),                   // 8: user.v0.ListRequest
	(*ListResponse)(nil),                  // 9: user.v0.ListResponse
	(*CreateRequest)(nil),                 // 10: user.v0.CreateRequest
	(*CreateResponse)(nil),                // 11: user.v0.CreateResponse
	(*UpdateRequest)(nil),                 // 12: user.v0.UpdateRequest
	(*UpdateResponse)(nil),                // 13: user.v0.UpdateResponse
	(*SetVerificationStatusRequest)(nil),  // 14: user.v0.SetVerificationStatusRequest
	(*SetVerificationStatusResponse)(nil), // 15: user.v0.SetVerificationStatusResponse
	(*SetRoleClaimRequest)(nil),           // 16: user.v0.SetRoleClaimRequest
	(*SetRoleClaimResponse)(nil),          // 17: user.v0.SetRoleClaimResponse
	(*DeleteRequest)(nil),                 // 18: user.v0.DeleteRequest
	(*DeleteResponse)(nil),                // 19: user.v0.DeleteResponse
	(*timestamppb.Timestamp)(nil),         // 20: google.protobuf.Timestamp
	(*v0.Address)(nil),                    // 21: address.v0.Address
	(*fieldmaskpb.FieldMask)(nil),         // 22: google.protobuf.FieldMask
}
var file_user_v0_user_proto_depIdxs = []int32{
	20, // 0: user.v0.User.created_at:type_name -> google.protobuf.Timestamp
	20, // 1: user.v0.User.updated_at:type_name -> google.protobuf.Timestamp
	20, // 2: user.v0.User.date_of_birth:type_name -> google.protobuf.Timestamp
	21, // 3: user.v0.User.addresses:type_name -> address.v0.Address
	20, // 4: user.v0.UserListItem.created_at:type_name -> google.protobuf.Timestamp
	20, // 5: user.v0.UserListItem.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 6: user.v0.GetResponse.user:type_name -> user.v0.User
	0,  // 7: user.v0.GetByEmailResponse.user:type_name -> user.v0.User
	1,  // 8: user.v0.GetReducedResponse.user:type_name -> user.v0.UserListItem
	1,  // 9: user.v0.ListResponse.users:type_name -> user.v0.UserListItem
	20, // 10: user.v0.CreateResponse.created_at:type_name -> google.protobuf.Timestamp
	20, // 11: user.v0.UpdateRequest.date_of_birth:type_name -> google.protobuf.Timestamp
	22, // 12: user.v0.UpdateRequest.update_mask:type_name -> google.protobuf.FieldMask
	20, // 13: user.v0.UpdateResponse.date_of_birth:type_name -> google.protobuf.Timestamp
	22, // 14: user.v0.UpdateResponse.updated:type_name -> google.protobuf.FieldMask
	2,  // 15: user.v0.UserService.Get:input_type -> user.v0.GetRequest
	6,  // 16: user.v0.UserService.GetReduced:input_type -> user.v0.GetReducedRequest
	8,  // 17: user.v0.UserService.List:input_type -> user.v0.ListRequest
	10, // 18: user.v0.UserService.Create:input_type -> user.v0.CreateRequest
	14, // 19: user.v0.UserService.SetVerificationStatus:input_type -> user.v0.SetVerificationStatusRequest
	16, // 20: user.v0.UserService.SetRoleClaim:input_type -> user.v0.SetRoleClaimRequest
	12, // 21: user.v0.UserService.Update:input_type -> user.v0.UpdateRequest
	18, // 22: user.v0.UserService.Delete:input_type -> user.v0.DeleteRequest
	3,  // 23: user.v0.UserService.Get:output_type -> user.v0.GetResponse
	7,  // 24: user.v0.UserService.GetReduced:output_type -> user.v0.GetReducedResponse
	9,  // 25: user.v0.UserService.List:output_type -> user.v0.ListResponse
	11, // 26: user.v0.UserService.Create:output_type -> user.v0.CreateResponse
	15, // 27: user.v0.UserService.SetVerificationStatus:output_type -> user.v0.SetVerificationStatusResponse
	17, // 28: user.v0.UserService.SetRoleClaim:output_type -> user.v0.SetRoleClaimResponse
	13, // 29: user.v0.UserService.Update:output_type -> user.v0.UpdateResponse
	19, // 30: user.v0.UserService.Delete:output_type -> user.v0.DeleteResponse
	23, // [23:31] is the sub-list for method output_type
	15, // [15:23] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_user_v0_user_proto_init() }
func file_user_v0_user_proto_init() {
	if File_user_v0_user_proto != nil {
		return
	}
	file_user_v0_user_proto_msgTypes[0].OneofWrappers = []any{}
	file_user_v0_user_proto_msgTypes[12].OneofWrappers = []any{}
	file_user_v0_user_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v0_user_proto_rawDesc), len(file_user_v0_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v0_user_proto_goTypes,
		DependencyIndexes: file_user_v0_user_proto_depIdxs,
		MessageInfos:      file_user_v0_user_proto_msgTypes,
	}.Build()
	File_user_v0_user_proto = out.File
	file_user_v0_user_proto_goTypes = nil
	file_user_v0_user_proto_depIdxs = nil
}
