// github.com/mikhail5545/proto-go
// shared proto module for vitainmove project microservices
// Copyright (C) 2025  Mikhail Kulik

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.

// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: product_service/course_part/v0/course_part.proto

package coursepartpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoursePartService_Get_FullMethodName            = "/course_part.v0.CoursePartService/Get"
	CoursePartService_GetWithDraft_FullMethodName   = "/course_part.v0.CoursePartService/GetWithDraft"
	CoursePartService_GetWithDeleted_FullMethodName = "/course_part.v0.CoursePartService/GetWithDeleted"
	CoursePartService_List_FullMethodName           = "/course_part.v0.CoursePartService/List"
	CoursePartService_ListDrafts_FullMethodName     = "/course_part.v0.CoursePartService/ListDrafts"
	CoursePartService_ListDeleted_FullMethodName    = "/course_part.v0.CoursePartService/ListDeleted"
	CoursePartService_Create_FullMethodName         = "/course_part.v0.CoursePartService/Create"
	CoursePartService_Update_FullMethodName         = "/course_part.v0.CoursePartService/Update"
	CoursePartService_Undraft_FullMethodName        = "/course_part.v0.CoursePartService/Undraft"
	CoursePartService_Archive_FullMethodName        = "/course_part.v0.CoursePartService/Archive"
	CoursePartService_Unarchive_FullMethodName      = "/course_part.v0.CoursePartService/Unarchive"
)

// CoursePartServiceClient is the client API for CoursePartService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoursePartServiceClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetWithDraft(ctx context.Context, in *GetWithDraftRequest, opts ...grpc.CallOption) (*GetWithDraftResponse, error)
	GetWithDeleted(ctx context.Context, in *GetWithDeletedRequest, opts ...grpc.CallOption) (*GetWithDeletedResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	ListDrafts(ctx context.Context, in *ListDraftRequest, opts ...grpc.CallOption) (*ListDraftResponse, error)
	ListDeleted(ctx context.Context, in *ListDeletedRequest, opts ...grpc.CallOption) (*ListDeletedResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Undraft(ctx context.Context, in *UndraftRequest, opts ...grpc.CallOption) (*UndraftResponse, error)
	Archive(ctx context.Context, in *ArchiveRequest, opts ...grpc.CallOption) (*ArchiveResponse, error)
	Unarchive(ctx context.Context, in *UnarchiveRequest, opts ...grpc.CallOption) (*UnarchiveResponse, error)
}

type coursePartServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoursePartServiceClient(cc grpc.ClientConnInterface) CoursePartServiceClient {
	return &coursePartServiceClient{cc}
}

func (c *coursePartServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, CoursePartService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coursePartServiceClient) GetWithDraft(ctx context.Context, in *GetWithDraftRequest, opts ...grpc.CallOption) (*GetWithDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWithDraftResponse)
	err := c.cc.Invoke(ctx, CoursePartService_GetWithDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coursePartServiceClient) GetWithDeleted(ctx context.Context, in *GetWithDeletedRequest, opts ...grpc.CallOption) (*GetWithDeletedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWithDeletedResponse)
	err := c.cc.Invoke(ctx, CoursePartService_GetWithDeleted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coursePartServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, CoursePartService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coursePartServiceClient) ListDrafts(ctx context.Context, in *ListDraftRequest, opts ...grpc.CallOption) (*ListDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDraftResponse)
	err := c.cc.Invoke(ctx, CoursePartService_ListDrafts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coursePartServiceClient) ListDeleted(ctx context.Context, in *ListDeletedRequest, opts ...grpc.CallOption) (*ListDeletedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeletedResponse)
	err := c.cc.Invoke(ctx, CoursePartService_ListDeleted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coursePartServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, CoursePartService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coursePartServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, CoursePartService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coursePartServiceClient) Undraft(ctx context.Context, in *UndraftRequest, opts ...grpc.CallOption) (*UndraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UndraftResponse)
	err := c.cc.Invoke(ctx, CoursePartService_Undraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coursePartServiceClient) Archive(ctx context.Context, in *ArchiveRequest, opts ...grpc.CallOption) (*ArchiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArchiveResponse)
	err := c.cc.Invoke(ctx, CoursePartService_Archive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coursePartServiceClient) Unarchive(ctx context.Context, in *UnarchiveRequest, opts ...grpc.CallOption) (*UnarchiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnarchiveResponse)
	err := c.cc.Invoke(ctx, CoursePartService_Unarchive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoursePartServiceServer is the server API for CoursePartService service.
// All implementations must embed UnimplementedCoursePartServiceServer
// for forward compatibility.
type CoursePartServiceServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	GetWithDraft(context.Context, *GetWithDraftRequest) (*GetWithDraftResponse, error)
	GetWithDeleted(context.Context, *GetWithDeletedRequest) (*GetWithDeletedResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	ListDrafts(context.Context, *ListDraftRequest) (*ListDraftResponse, error)
	ListDeleted(context.Context, *ListDeletedRequest) (*ListDeletedResponse, error)
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Undraft(context.Context, *UndraftRequest) (*UndraftResponse, error)
	Archive(context.Context, *ArchiveRequest) (*ArchiveResponse, error)
	Unarchive(context.Context, *UnarchiveRequest) (*UnarchiveResponse, error)
	mustEmbedUnimplementedCoursePartServiceServer()
}

// UnimplementedCoursePartServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoursePartServiceServer struct{}

func (UnimplementedCoursePartServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedCoursePartServiceServer) GetWithDraft(context.Context, *GetWithDraftRequest) (*GetWithDraftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWithDraft not implemented")
}
func (UnimplementedCoursePartServiceServer) GetWithDeleted(context.Context, *GetWithDeletedRequest) (*GetWithDeletedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWithDeleted not implemented")
}
func (UnimplementedCoursePartServiceServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedCoursePartServiceServer) ListDrafts(context.Context, *ListDraftRequest) (*ListDraftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDrafts not implemented")
}
func (UnimplementedCoursePartServiceServer) ListDeleted(context.Context, *ListDeletedRequest) (*ListDeletedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDeleted not implemented")
}
func (UnimplementedCoursePartServiceServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCoursePartServiceServer) Update(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedCoursePartServiceServer) Undraft(context.Context, *UndraftRequest) (*UndraftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Undraft not implemented")
}
func (UnimplementedCoursePartServiceServer) Archive(context.Context, *ArchiveRequest) (*ArchiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Archive not implemented")
}
func (UnimplementedCoursePartServiceServer) Unarchive(context.Context, *UnarchiveRequest) (*UnarchiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unarchive not implemented")
}
func (UnimplementedCoursePartServiceServer) mustEmbedUnimplementedCoursePartServiceServer() {}
func (UnimplementedCoursePartServiceServer) testEmbeddedByValue()                           {}

// UnsafeCoursePartServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoursePartServiceServer will
// result in compilation errors.
type UnsafeCoursePartServiceServer interface {
	mustEmbedUnimplementedCoursePartServiceServer()
}

func RegisterCoursePartServiceServer(s grpc.ServiceRegistrar, srv CoursePartServiceServer) {
	// If the following call pancis, it indicates UnimplementedCoursePartServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoursePartService_ServiceDesc, srv)
}

func _CoursePartService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoursePartServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoursePartService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoursePartServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoursePartService_GetWithDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoursePartServiceServer).GetWithDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoursePartService_GetWithDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoursePartServiceServer).GetWithDraft(ctx, req.(*GetWithDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoursePartService_GetWithDeleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithDeletedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoursePartServiceServer).GetWithDeleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoursePartService_GetWithDeleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoursePartServiceServer).GetWithDeleted(ctx, req.(*GetWithDeletedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoursePartService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoursePartServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoursePartService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoursePartServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoursePartService_ListDrafts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoursePartServiceServer).ListDrafts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoursePartService_ListDrafts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoursePartServiceServer).ListDrafts(ctx, req.(*ListDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoursePartService_ListDeleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeletedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoursePartServiceServer).ListDeleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoursePartService_ListDeleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoursePartServiceServer).ListDeleted(ctx, req.(*ListDeletedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoursePartService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoursePartServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoursePartService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoursePartServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoursePartService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoursePartServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoursePartService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoursePartServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoursePartService_Undraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoursePartServiceServer).Undraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoursePartService_Undraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoursePartServiceServer).Undraft(ctx, req.(*UndraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoursePartService_Archive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoursePartServiceServer).Archive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoursePartService_Archive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoursePartServiceServer).Archive(ctx, req.(*ArchiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoursePartService_Unarchive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnarchiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoursePartServiceServer).Unarchive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoursePartService_Unarchive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoursePartServiceServer).Unarchive(ctx, req.(*UnarchiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoursePartService_ServiceDesc is the grpc.ServiceDesc for CoursePartService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoursePartService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "course_part.v0.CoursePartService",
	HandlerType: (*CoursePartServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _CoursePartService_Get_Handler,
		},
		{
			MethodName: "GetWithDraft",
			Handler:    _CoursePartService_GetWithDraft_Handler,
		},
		{
			MethodName: "GetWithDeleted",
			Handler:    _CoursePartService_GetWithDeleted_Handler,
		},
		{
			MethodName: "List",
			Handler:    _CoursePartService_List_Handler,
		},
		{
			MethodName: "ListDrafts",
			Handler:    _CoursePartService_ListDrafts_Handler,
		},
		{
			MethodName: "ListDeleted",
			Handler:    _CoursePartService_ListDeleted_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _CoursePartService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CoursePartService_Update_Handler,
		},
		{
			MethodName: "Undraft",
			Handler:    _CoursePartService_Undraft_Handler,
		},
		{
			MethodName: "Archive",
			Handler:    _CoursePartService_Archive_Handler,
		},
		{
			MethodName: "Unarchive",
			Handler:    _CoursePartService_Unarchive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product_service/course_part/v0/course_part.proto",
}
