// github.com/mikhail5545/proto-go
// shared proto module for vitainmove project microservices
// Copyright (C) 2025  Mikhail Kulik

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.

// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: address/v0/address.proto

package addresspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	IsDefault     bool                   `protobuf:"varint,6,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	Country       string                 `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	City          string                 `protobuf:"bytes,8,opt,name=city,proto3" json:"city,omitempty"`
	PostalCode    string                 `protobuf:"bytes,9,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Street        string                 `protobuf:"bytes,10,opt,name=street,proto3" json:"street,omitempty"`
	House         string                 `protobuf:"bytes,11,opt,name=house,proto3" json:"house,omitempty"`
	Apartment     *string                `protobuf:"bytes,12,opt,name=apartment,proto3,oneof" json:"apartment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_address_v0_address_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_address_v0_address_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_address_v0_address_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Address) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Address) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Address) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Address) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Address) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetHouse() string {
	if x != nil {
		return x.House
	}
	return ""
}

func (x *Address) GetApartment() string {
	if x != nil && x.Apartment != nil {
		return *x.Apartment
	}
	return ""
}

type GetAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressRequest) Reset() {
	*x = GetAddressRequest{}
	mi := &file_address_v0_address_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressRequest) ProtoMessage() {}

func (x *GetAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_address_v0_address_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressRequest.ProtoReflect.Descriptor instead.
func (*GetAddressRequest) Descriptor() ([]byte, []int) {
	return file_address_v0_address_proto_rawDescGZIP(), []int{1}
}

func (x *GetAddressRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressResponse) Reset() {
	*x = GetAddressResponse{}
	mi := &file_address_v0_address_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressResponse) ProtoMessage() {}

func (x *GetAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_address_v0_address_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressResponse.ProtoReflect.Descriptor instead.
func (*GetAddressResponse) Descriptor() ([]byte, []int) {
	return file_address_v0_address_proto_rawDescGZIP(), []int{2}
}

func (x *GetAddressResponse) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type ListAddressesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddressesRequest) Reset() {
	*x = ListAddressesRequest{}
	mi := &file_address_v0_address_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddressesRequest) ProtoMessage() {}

func (x *ListAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_address_v0_address_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddressesRequest.ProtoReflect.Descriptor instead.
func (*ListAddressesRequest) Descriptor() ([]byte, []int) {
	return file_address_v0_address_proto_rawDescGZIP(), []int{3}
}

func (x *ListAddressesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAddressesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListAddressesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []*Address             `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddressesResponse) Reset() {
	*x = ListAddressesResponse{}
	mi := &file_address_v0_address_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddressesResponse) ProtoMessage() {}

func (x *ListAddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_address_v0_address_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddressesResponse.ProtoReflect.Descriptor instead.
func (*ListAddressesResponse) Descriptor() ([]byte, []int) {
	return file_address_v0_address_proto_rawDescGZIP(), []int{4}
}

func (x *ListAddressesResponse) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type ListUserAddressesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserAddressesRequest) Reset() {
	*x = ListUserAddressesRequest{}
	mi := &file_address_v0_address_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserAddressesRequest) ProtoMessage() {}

func (x *ListUserAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_address_v0_address_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserAddressesRequest.ProtoReflect.Descriptor instead.
func (*ListUserAddressesRequest) Descriptor() ([]byte, []int) {
	return file_address_v0_address_proto_rawDescGZIP(), []int{5}
}

func (x *ListUserAddressesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListUserAddressesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUserAddressesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListUserAddressesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []*Address             `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserAddressesResponse) Reset() {
	*x = ListUserAddressesResponse{}
	mi := &file_address_v0_address_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserAddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserAddressesResponse) ProtoMessage() {}

func (x *ListUserAddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_address_v0_address_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserAddressesResponse.ProtoReflect.Descriptor instead.
func (*ListUserAddressesResponse) Descriptor() ([]byte, []int) {
	return file_address_v0_address_proto_rawDescGZIP(), []int{6}
}

func (x *ListUserAddressesResponse) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type CreateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	IsDefault     bool                   `protobuf:"varint,3,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	PostalCode    string                 `protobuf:"bytes,6,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Street        string                 `protobuf:"bytes,7,opt,name=street,proto3" json:"street,omitempty"`
	House         string                 `protobuf:"bytes,8,opt,name=house,proto3" json:"house,omitempty"`
	Apartment     *string                `protobuf:"bytes,9,opt,name=apartment,proto3,oneof" json:"apartment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressRequest) Reset() {
	*x = CreateAddressRequest{}
	mi := &file_address_v0_address_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressRequest) ProtoMessage() {}

func (x *CreateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_address_v0_address_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressRequest.ProtoReflect.Descriptor instead.
func (*CreateAddressRequest) Descriptor() ([]byte, []int) {
	return file_address_v0_address_proto_rawDescGZIP(), []int{7}
}

func (x *CreateAddressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAddressRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateAddressRequest) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *CreateAddressRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreateAddressRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateAddressRequest) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *CreateAddressRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *CreateAddressRequest) GetHouse() string {
	if x != nil {
		return x.House
	}
	return ""
}

func (x *CreateAddressRequest) GetApartment() string {
	if x != nil && x.Apartment != nil {
		return *x.Apartment
	}
	return ""
}

type CreateAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressResponse) Reset() {
	*x = CreateAddressResponse{}
	mi := &file_address_v0_address_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressResponse) ProtoMessage() {}

func (x *CreateAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_address_v0_address_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressResponse.ProtoReflect.Descriptor instead.
func (*CreateAddressResponse) Descriptor() ([]byte, []int) {
	return file_address_v0_address_proto_rawDescGZIP(), []int{8}
}

func (x *CreateAddressResponse) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type UpdateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          *string                `protobuf:"bytes,2,opt,name=type,proto3,oneof" json:"type,omitempty"`
	IsDefault     *bool                  `protobuf:"varint,3,opt,name=is_default,json=isDefault,proto3,oneof" json:"is_default,omitempty"`
	Country       *string                `protobuf:"bytes,4,opt,name=country,proto3,oneof" json:"country,omitempty"`
	City          *string                `protobuf:"bytes,5,opt,name=city,proto3,oneof" json:"city,omitempty"`
	PostalCode    *string                `protobuf:"bytes,6,opt,name=postal_code,json=postalCode,proto3,oneof" json:"postal_code,omitempty"`
	Street        *string                `protobuf:"bytes,7,opt,name=street,proto3,oneof" json:"street,omitempty"`
	House         *string                `protobuf:"bytes,8,opt,name=house,proto3,oneof" json:"house,omitempty"`
	Apartment     *string                `protobuf:"bytes,9,opt,name=apartment,proto3,oneof" json:"apartment,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,10,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAddressRequest) Reset() {
	*x = UpdateAddressRequest{}
	mi := &file_address_v0_address_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressRequest) ProtoMessage() {}

func (x *UpdateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_address_v0_address_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressRequest.ProtoReflect.Descriptor instead.
func (*UpdateAddressRequest) Descriptor() ([]byte, []int) {
	return file_address_v0_address_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateAddressRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAddressRequest) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *UpdateAddressRequest) GetIsDefault() bool {
	if x != nil && x.IsDefault != nil {
		return *x.IsDefault
	}
	return false
}

func (x *UpdateAddressRequest) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *UpdateAddressRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *UpdateAddressRequest) GetPostalCode() string {
	if x != nil && x.PostalCode != nil {
		return *x.PostalCode
	}
	return ""
}

func (x *UpdateAddressRequest) GetStreet() string {
	if x != nil && x.Street != nil {
		return *x.Street
	}
	return ""
}

func (x *UpdateAddressRequest) GetHouse() string {
	if x != nil && x.House != nil {
		return *x.House
	}
	return ""
}

func (x *UpdateAddressRequest) GetApartment() string {
	if x != nil && x.Apartment != nil {
		return *x.Apartment
	}
	return ""
}

func (x *UpdateAddressRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type MakeDefaultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeDefaultRequest) Reset() {
	*x = MakeDefaultRequest{}
	mi := &file_address_v0_address_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeDefaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeDefaultRequest) ProtoMessage() {}

func (x *MakeDefaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_address_v0_address_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeDefaultRequest.ProtoReflect.Descriptor instead.
func (*MakeDefaultRequest) Descriptor() ([]byte, []int) {
	return file_address_v0_address_proto_rawDescGZIP(), []int{10}
}

func (x *MakeDefaultRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MakeDefaultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsDefault     bool                   `protobuf:"varint,3,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeDefaultResponse) Reset() {
	*x = MakeDefaultResponse{}
	mi := &file_address_v0_address_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeDefaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeDefaultResponse) ProtoMessage() {}

func (x *MakeDefaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_address_v0_address_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeDefaultResponse.ProtoReflect.Descriptor instead.
func (*MakeDefaultResponse) Descriptor() ([]byte, []int) {
	return file_address_v0_address_proto_rawDescGZIP(), []int{11}
}

func (x *MakeDefaultResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MakeDefaultResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MakeDefaultResponse) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type UpdateAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAddressResponse) Reset() {
	*x = UpdateAddressResponse{}
	mi := &file_address_v0_address_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressResponse) ProtoMessage() {}

func (x *UpdateAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_address_v0_address_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressResponse.ProtoReflect.Descriptor instead.
func (*UpdateAddressResponse) Descriptor() ([]byte, []int) {
	return file_address_v0_address_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateAddressResponse) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type DeleteAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddressRequest) Reset() {
	*x = DeleteAddressRequest{}
	mi := &file_address_v0_address_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressRequest) ProtoMessage() {}

func (x *DeleteAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_address_v0_address_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressRequest.ProtoReflect.Descriptor instead.
func (*DeleteAddressRequest) Descriptor() ([]byte, []int) {
	return file_address_v0_address_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteAddressRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddressResponse) Reset() {
	*x = DeleteAddressResponse{}
	mi := &file_address_v0_address_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressResponse) ProtoMessage() {}

func (x *DeleteAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_address_v0_address_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressResponse.ProtoReflect.Descriptor instead.
func (*DeleteAddressResponse) Descriptor() ([]byte, []int) {
	return file_address_v0_address_proto_rawDescGZIP(), []int{14}
}

var File_address_v0_address_proto protoreflect.FileDescriptor

const file_address_v0_address_proto_rawDesc = "" +
	"\n" +
	"\x18address/v0/address.proto\x12\n" +
	"address.v0\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\"\x89\x03\n" +
	"\aAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"is_default\x18\x06 \x01(\bR\tisDefault\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\b \x01(\tR\x04city\x12\x1f\n" +
	"\vpostal_code\x18\t \x01(\tR\n" +
	"postalCode\x12\x16\n" +
	"\x06street\x18\n" +
	" \x01(\tR\x06street\x12\x14\n" +
	"\x05house\x18\v \x01(\tR\x05house\x12!\n" +
	"\tapartment\x18\f \x01(\tH\x00R\tapartment\x88\x01\x01B\f\n" +
	"\n" +
	"_apartment\"#\n" +
	"\x11GetAddressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x12GetAddressResponse\x12-\n" +
	"\aaddress\x18\x01 \x01(\v2\x13.address.v0.AddressR\aaddress\"D\n" +
	"\x14ListAddressesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"J\n" +
	"\x15ListAddressesResponse\x121\n" +
	"\taddresses\x18\x01 \x03(\v2\x13.address.v0.AddressR\taddresses\"a\n" +
	"\x18ListUserAddressesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"N\n" +
	"\x19ListUserAddressesResponse\x121\n" +
	"\taddresses\x18\x01 \x03(\v2\x13.address.v0.AddressR\taddresses\"\x90\x02\n" +
	"\x14CreateAddressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"is_default\x18\x03 \x01(\bR\tisDefault\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x1f\n" +
	"\vpostal_code\x18\x06 \x01(\tR\n" +
	"postalCode\x12\x16\n" +
	"\x06street\x18\a \x01(\tR\x06street\x12\x14\n" +
	"\x05house\x18\b \x01(\tR\x05house\x12!\n" +
	"\tapartment\x18\t \x01(\tH\x00R\tapartment\x88\x01\x01B\f\n" +
	"\n" +
	"_apartment\"F\n" +
	"\x15CreateAddressResponse\x12-\n" +
	"\aaddress\x18\x01 \x01(\v2\x13.address.v0.AddressR\aaddress\"\xb9\x03\n" +
	"\x14UpdateAddressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04type\x18\x02 \x01(\tH\x00R\x04type\x88\x01\x01\x12\"\n" +
	"\n" +
	"is_default\x18\x03 \x01(\bH\x01R\tisDefault\x88\x01\x01\x12\x1d\n" +
	"\acountry\x18\x04 \x01(\tH\x02R\acountry\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\x05 \x01(\tH\x03R\x04city\x88\x01\x01\x12$\n" +
	"\vpostal_code\x18\x06 \x01(\tH\x04R\n" +
	"postalCode\x88\x01\x01\x12\x1b\n" +
	"\x06street\x18\a \x01(\tH\x05R\x06street\x88\x01\x01\x12\x19\n" +
	"\x05house\x18\b \x01(\tH\x06R\x05house\x88\x01\x01\x12!\n" +
	"\tapartment\x18\t \x01(\tH\aR\tapartment\x88\x01\x01\x12;\n" +
	"\vupdate_mask\x18\n" +
	" \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMaskB\a\n" +
	"\x05_typeB\r\n" +
	"\v_is_defaultB\n" +
	"\n" +
	"\b_countryB\a\n" +
	"\x05_cityB\x0e\n" +
	"\f_postal_codeB\t\n" +
	"\a_streetB\b\n" +
	"\x06_houseB\f\n" +
	"\n" +
	"_apartment\"$\n" +
	"\x12MakeDefaultRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"]\n" +
	"\x13MakeDefaultResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"is_default\x18\x03 \x01(\bR\tisDefault\"F\n" +
	"\x15UpdateAddressResponse\x12-\n" +
	"\aaddress\x18\x01 \x01(\v2\x13.address.v0.AddressR\aaddress\"&\n" +
	"\x14DeleteAddressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x17\n" +
	"\x15DeleteAddressResponse2\xf5\x04\n" +
	"\x0eAddressService\x12M\n" +
	"\n" +
	"GetAddress\x12\x1d.address.v0.GetAddressRequest\x1a\x1e.address.v0.GetAddressResponse\"\x00\x12V\n" +
	"\rListAddresses\x12 .address.v0.ListAddressesRequest\x1a!.address.v0.ListAddressesResponse\"\x00\x12b\n" +
	"\x11ListUserAddresses\x12$.address.v0.ListUserAddressesRequest\x1a%.address.v0.ListUserAddressesResponse\"\x00\x12V\n" +
	"\rCreateAddress\x12 .address.v0.CreateAddressRequest\x1a!.address.v0.CreateAddressResponse\"\x00\x12V\n" +
	"\rUpdateAddress\x12 .address.v0.UpdateAddressRequest\x1a!.address.v0.UpdateAddressResponse\"\x00\x12P\n" +
	"\vMakeDefault\x12\x1e.address.v0.MakeDefaultRequest\x1a\x1f.address.v0.MakeDefaultResponse\"\x00\x12V\n" +
	"\rDeleteAddress\x12 .address.v0.DeleteAddressRequest\x1a!.address.v0.DeleteAddressResponse\"\x00B<Z:github.com/mikhail5545/proto-go/proto/address/v0;addresspbb\x06proto3"

var (
	file_address_v0_address_proto_rawDescOnce sync.Once
	file_address_v0_address_proto_rawDescData []byte
)

func file_address_v0_address_proto_rawDescGZIP() []byte {
	file_address_v0_address_proto_rawDescOnce.Do(func() {
		file_address_v0_address_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_address_v0_address_proto_rawDesc), len(file_address_v0_address_proto_rawDesc)))
	})
	return file_address_v0_address_proto_rawDescData
}

var file_address_v0_address_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_address_v0_address_proto_goTypes = []any{
	(*Address)(nil),                   // 0: address.v0.Address
	(*GetAddressRequest)(nil),         // 1: address.v0.GetAddressRequest
	(*GetAddressResponse)(nil),        // 2: address.v0.GetAddressResponse
	(*ListAddressesRequest)(nil),      // 3: address.v0.ListAddressesRequest
	(*ListAddressesResponse)(nil),     // 4: address.v0.ListAddressesResponse
	(*ListUserAddressesRequest)(nil),  // 5: address.v0.ListUserAddressesRequest
	(*ListUserAddressesResponse)(nil), // 6: address.v0.ListUserAddressesResponse
	(*CreateAddressRequest)(nil),      // 7: address.v0.CreateAddressRequest
	(*CreateAddressResponse)(nil),     // 8: address.v0.CreateAddressResponse
	(*UpdateAddressRequest)(nil),      // 9: address.v0.UpdateAddressRequest
	(*MakeDefaultRequest)(nil),        // 10: address.v0.MakeDefaultRequest
	(*MakeDefaultResponse)(nil),       // 11: address.v0.MakeDefaultResponse
	(*UpdateAddressResponse)(nil),     // 12: address.v0.UpdateAddressResponse
	(*DeleteAddressRequest)(nil),      // 13: address.v0.DeleteAddressRequest
	(*DeleteAddressResponse)(nil),     // 14: address.v0.DeleteAddressResponse
	(*timestamppb.Timestamp)(nil),     // 15: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),     // 16: google.protobuf.FieldMask
}
var file_address_v0_address_proto_depIdxs = []int32{
	15, // 0: address.v0.Address.created_at:type_name -> google.protobuf.Timestamp
	15, // 1: address.v0.Address.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: address.v0.GetAddressResponse.address:type_name -> address.v0.Address
	0,  // 3: address.v0.ListAddressesResponse.addresses:type_name -> address.v0.Address
	0,  // 4: address.v0.ListUserAddressesResponse.addresses:type_name -> address.v0.Address
	0,  // 5: address.v0.CreateAddressResponse.address:type_name -> address.v0.Address
	16, // 6: address.v0.UpdateAddressRequest.update_mask:type_name -> google.protobuf.FieldMask
	0,  // 7: address.v0.UpdateAddressResponse.address:type_name -> address.v0.Address
	1,  // 8: address.v0.AddressService.GetAddress:input_type -> address.v0.GetAddressRequest
	3,  // 9: address.v0.AddressService.ListAddresses:input_type -> address.v0.ListAddressesRequest
	5,  // 10: address.v0.AddressService.ListUserAddresses:input_type -> address.v0.ListUserAddressesRequest
	7,  // 11: address.v0.AddressService.CreateAddress:input_type -> address.v0.CreateAddressRequest
	9,  // 12: address.v0.AddressService.UpdateAddress:input_type -> address.v0.UpdateAddressRequest
	10, // 13: address.v0.AddressService.MakeDefault:input_type -> address.v0.MakeDefaultRequest
	13, // 14: address.v0.AddressService.DeleteAddress:input_type -> address.v0.DeleteAddressRequest
	2,  // 15: address.v0.AddressService.GetAddress:output_type -> address.v0.GetAddressResponse
	4,  // 16: address.v0.AddressService.ListAddresses:output_type -> address.v0.ListAddressesResponse
	6,  // 17: address.v0.AddressService.ListUserAddresses:output_type -> address.v0.ListUserAddressesResponse
	8,  // 18: address.v0.AddressService.CreateAddress:output_type -> address.v0.CreateAddressResponse
	12, // 19: address.v0.AddressService.UpdateAddress:output_type -> address.v0.UpdateAddressResponse
	11, // 20: address.v0.AddressService.MakeDefault:output_type -> address.v0.MakeDefaultResponse
	14, // 21: address.v0.AddressService.DeleteAddress:output_type -> address.v0.DeleteAddressResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_address_v0_address_proto_init() }
func file_address_v0_address_proto_init() {
	if File_address_v0_address_proto != nil {
		return
	}
	file_address_v0_address_proto_msgTypes[0].OneofWrappers = []any{}
	file_address_v0_address_proto_msgTypes[7].OneofWrappers = []any{}
	file_address_v0_address_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_address_v0_address_proto_rawDesc), len(file_address_v0_address_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_address_v0_address_proto_goTypes,
		DependencyIndexes: file_address_v0_address_proto_depIdxs,
		MessageInfos:      file_address_v0_address_proto_msgTypes,
	}.Build()
	File_address_v0_address_proto = out.File
	file_address_v0_address_proto_goTypes = nil
	file_address_v0_address_proto_depIdxs = nil
}
