// github.com/mikhail5545/proto-go
// shared proto module for vitainmove project microservices
// Copyright (C) 2025  Mikhail Kulik

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.

// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: media_service/mux/asset/v0/asset.proto

package assetpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Asset struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	MuxUploadId        *string                `protobuf:"bytes,5,opt,name=mux_upload_id,json=muxUploadId,proto3,oneof" json:"mux_upload_id,omitempty"`
	MuxAssetId         *string                `protobuf:"bytes,6,opt,name=mux_asset_id,json=muxAssetId,proto3,oneof" json:"mux_asset_id,omitempty"`
	MuxPlaybackId      *string                `protobuf:"bytes,7,opt,name=mux_playback_id,json=muxPlaybackId,proto3,oneof" json:"mux_playback_id,omitempty"`
	State              string                 `protobuf:"bytes,8,opt,name=state,proto3" json:"state,omitempty"`
	Status             *string                `protobuf:"bytes,9,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Duration           *float32               `protobuf:"fixed32,10,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	AspectRatio        *string                `protobuf:"bytes,11,opt,name=aspect_ratio,json=aspectRatio,proto3,oneof" json:"aspect_ratio,omitempty"`
	Height             *int32                 `protobuf:"varint,12,opt,name=height,proto3,oneof" json:"height,omitempty"`
	Width              *int32                 `protobuf:"varint,13,opt,name=width,proto3,oneof" json:"width,omitempty"`
	AssetCreatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=asset_created_at,json=assetCreatedAt,proto3,oneof" json:"asset_created_at,omitempty"`
	MaxResolutionTier  *string                `protobuf:"bytes,15,opt,name=max_resolution_tier,json=maxResolutionTier,proto3,oneof" json:"max_resolution_tier,omitempty"`
	MaxStoredFrameRate *string                `protobuf:"bytes,16,opt,name=max_stored_frame_rate,json=maxStoredFrameRate,proto3,oneof" json:"max_stored_frame_rate,omitempty"`
	IngestType         *string                `protobuf:"bytes,17,opt,name=ingest_type,json=ingestType,proto3,oneof" json:"ingest_type,omitempty"`
	Passthrough        *string                `protobuf:"bytes,18,opt,name=passthrough,proto3,oneof" json:"passthrough,omitempty"`
	OwnerId            *string                `protobuf:"bytes,19,opt,name=owner_id,json=ownerId,proto3,oneof" json:"owner_id,omitempty"`
	OwnerType          *string                `protobuf:"bytes,20,opt,name=owner_type,json=ownerType,proto3,oneof" json:"owner_type,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_media_service_mux_asset_v0_asset_proto_rawDescGZIP(), []int{0}
}

func (x *Asset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Asset) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Asset) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Asset) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Asset) GetMuxUploadId() string {
	if x != nil && x.MuxUploadId != nil {
		return *x.MuxUploadId
	}
	return ""
}

func (x *Asset) GetMuxAssetId() string {
	if x != nil && x.MuxAssetId != nil {
		return *x.MuxAssetId
	}
	return ""
}

func (x *Asset) GetMuxPlaybackId() string {
	if x != nil && x.MuxPlaybackId != nil {
		return *x.MuxPlaybackId
	}
	return ""
}

func (x *Asset) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Asset) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *Asset) GetDuration() float32 {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return 0
}

func (x *Asset) GetAspectRatio() string {
	if x != nil && x.AspectRatio != nil {
		return *x.AspectRatio
	}
	return ""
}

func (x *Asset) GetHeight() int32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

func (x *Asset) GetWidth() int32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *Asset) GetAssetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AssetCreatedAt
	}
	return nil
}

func (x *Asset) GetMaxResolutionTier() string {
	if x != nil && x.MaxResolutionTier != nil {
		return *x.MaxResolutionTier
	}
	return ""
}

func (x *Asset) GetMaxStoredFrameRate() string {
	if x != nil && x.MaxStoredFrameRate != nil {
		return *x.MaxStoredFrameRate
	}
	return ""
}

func (x *Asset) GetIngestType() string {
	if x != nil && x.IngestType != nil {
		return *x.IngestType
	}
	return ""
}

func (x *Asset) GetPassthrough() string {
	if x != nil && x.Passthrough != nil {
		return *x.Passthrough
	}
	return ""
}

func (x *Asset) GetOwnerId() string {
	if x != nil && x.OwnerId != nil {
		return *x.OwnerId
	}
	return ""
}

func (x *Asset) GetOwnerType() string {
	if x != nil && x.OwnerType != nil {
		return *x.OwnerType
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_media_service_mux_asset_v0_asset_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *Asset                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_media_service_mux_asset_v0_asset_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

type GetWithDeletedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWithDeletedRequest) Reset() {
	*x = GetWithDeletedRequest{}
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWithDeletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWithDeletedRequest) ProtoMessage() {}

func (x *GetWithDeletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWithDeletedRequest.ProtoReflect.Descriptor instead.
func (*GetWithDeletedRequest) Descriptor() ([]byte, []int) {
	return file_media_service_mux_asset_v0_asset_proto_rawDescGZIP(), []int{3}
}

func (x *GetWithDeletedRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetWithDeletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *Asset                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWithDeletedResponse) Reset() {
	*x = GetWithDeletedResponse{}
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWithDeletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWithDeletedResponse) ProtoMessage() {}

func (x *GetWithDeletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWithDeletedResponse.ProtoReflect.Descriptor instead.
func (*GetWithDeletedResponse) Descriptor() ([]byte, []int) {
	return file_media_service_mux_asset_v0_asset_proto_rawDescGZIP(), []int{4}
}

func (x *GetWithDeletedResponse) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_media_service_mux_asset_v0_asset_proto_rawDescGZIP(), []int{5}
}

func (x *ListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*Asset               `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_media_service_mux_asset_v0_asset_proto_rawDescGZIP(), []int{6}
}

func (x *ListResponse) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *ListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListDeletedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeletedRequest) Reset() {
	*x = ListDeletedRequest{}
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeletedRequest) ProtoMessage() {}

func (x *ListDeletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeletedRequest.ProtoReflect.Descriptor instead.
func (*ListDeletedRequest) Descriptor() ([]byte, []int) {
	return file_media_service_mux_asset_v0_asset_proto_rawDescGZIP(), []int{7}
}

func (x *ListDeletedRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDeletedRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListDeletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*Asset               `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeletedResponse) Reset() {
	*x = ListDeletedResponse{}
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeletedResponse) ProtoMessage() {}

func (x *ListDeletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeletedResponse.ProtoReflect.Descriptor instead.
func (*ListDeletedResponse) Descriptor() ([]byte, []int) {
	return file_media_service_mux_asset_v0_asset_proto_rawDescGZIP(), []int{8}
}

func (x *ListDeletedResponse) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *ListDeletedResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListUnownedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUnownedRequest) Reset() {
	*x = ListUnownedRequest{}
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUnownedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUnownedRequest) ProtoMessage() {}

func (x *ListUnownedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUnownedRequest.ProtoReflect.Descriptor instead.
func (*ListUnownedRequest) Descriptor() ([]byte, []int) {
	return file_media_service_mux_asset_v0_asset_proto_rawDescGZIP(), []int{9}
}

func (x *ListUnownedRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUnownedRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListUnownedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*Asset               `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUnownedResponse) Reset() {
	*x = ListUnownedResponse{}
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUnownedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUnownedResponse) ProtoMessage() {}

func (x *ListUnownedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUnownedResponse.ProtoReflect.Descriptor instead.
func (*ListUnownedResponse) Descriptor() ([]byte, []int) {
	return file_media_service_mux_asset_v0_asset_proto_rawDescGZIP(), []int{10}
}

func (x *ListUnownedResponse) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *ListUnownedResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_media_service_mux_asset_v0_asset_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_media_service_mux_asset_v0_asset_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePermanentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermanentRequest) Reset() {
	*x = DeletePermanentRequest{}
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermanentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermanentRequest) ProtoMessage() {}

func (x *DeletePermanentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermanentRequest.ProtoReflect.Descriptor instead.
func (*DeletePermanentRequest) Descriptor() ([]byte, []int) {
	return file_media_service_mux_asset_v0_asset_proto_rawDescGZIP(), []int{13}
}

func (x *DeletePermanentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePermanentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermanentResponse) Reset() {
	*x = DeletePermanentResponse{}
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermanentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermanentResponse) ProtoMessage() {}

func (x *DeletePermanentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermanentResponse.ProtoReflect.Descriptor instead.
func (*DeletePermanentResponse) Descriptor() ([]byte, []int) {
	return file_media_service_mux_asset_v0_asset_proto_rawDescGZIP(), []int{14}
}

func (x *DeletePermanentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RestoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_media_service_mux_asset_v0_asset_proto_rawDescGZIP(), []int{15}
}

func (x *RestoreRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_media_service_mux_asset_v0_asset_proto_rawDescGZIP(), []int{16}
}

func (x *RestoreResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateUploadUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	OwnerType     string                 `protobuf:"bytes,2,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUploadUrlRequest) Reset() {
	*x = CreateUploadUrlRequest{}
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadUrlRequest) ProtoMessage() {}

func (x *CreateUploadUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadUrlRequest.ProtoReflect.Descriptor instead.
func (*CreateUploadUrlRequest) Descriptor() ([]byte, []int) {
	return file_media_service_mux_asset_v0_asset_proto_rawDescGZIP(), []int{17}
}

func (x *CreateUploadUrlRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateUploadUrlRequest) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

type CreateUploadUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       *string                `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3,oneof" json:"owner_id,omitempty"`
	OwnerType     *string                `protobuf:"bytes,3,opt,name=owner_type,json=ownerType,proto3,oneof" json:"owner_type,omitempty"`
	State         *string                `protobuf:"bytes,4,opt,name=state,proto3,oneof" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUploadUrlResponse) Reset() {
	*x = CreateUploadUrlResponse{}
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadUrlResponse) ProtoMessage() {}

func (x *CreateUploadUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_service_mux_asset_v0_asset_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadUrlResponse.ProtoReflect.Descriptor instead.
func (*CreateUploadUrlResponse) Descriptor() ([]byte, []int) {
	return file_media_service_mux_asset_v0_asset_proto_rawDescGZIP(), []int{18}
}

func (x *CreateUploadUrlResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateUploadUrlResponse) GetOwnerId() string {
	if x != nil && x.OwnerId != nil {
		return *x.OwnerId
	}
	return ""
}

func (x *CreateUploadUrlResponse) GetOwnerType() string {
	if x != nil && x.OwnerType != nil {
		return *x.OwnerType
	}
	return ""
}

func (x *CreateUploadUrlResponse) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

var File_media_service_mux_asset_v0_asset_proto protoreflect.FileDescriptor

const file_media_service_mux_asset_v0_asset_proto_rawDesc = "" +
	"\n" +
	"&media_service/mux/asset/v0/asset.proto\x12\basset.v0\x1a\x1fgoogle/protobuf/timestamp.proto\"\xce\b\n" +
	"\x05Asset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tdeletedAt\x88\x01\x01\x12'\n" +
	"\rmux_upload_id\x18\x05 \x01(\tH\x01R\vmuxUploadId\x88\x01\x01\x12%\n" +
	"\fmux_asset_id\x18\x06 \x01(\tH\x02R\n" +
	"muxAssetId\x88\x01\x01\x12+\n" +
	"\x0fmux_playback_id\x18\a \x01(\tH\x03R\rmuxPlaybackId\x88\x01\x01\x12\x14\n" +
	"\x05state\x18\b \x01(\tR\x05state\x12\x1b\n" +
	"\x06status\x18\t \x01(\tH\x04R\x06status\x88\x01\x01\x12\x1f\n" +
	"\bduration\x18\n" +
	" \x01(\x02H\x05R\bduration\x88\x01\x01\x12&\n" +
	"\faspect_ratio\x18\v \x01(\tH\x06R\vaspectRatio\x88\x01\x01\x12\x1b\n" +
	"\x06height\x18\f \x01(\x05H\aR\x06height\x88\x01\x01\x12\x19\n" +
	"\x05width\x18\r \x01(\x05H\bR\x05width\x88\x01\x01\x12I\n" +
	"\x10asset_created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampH\tR\x0eassetCreatedAt\x88\x01\x01\x123\n" +
	"\x13max_resolution_tier\x18\x0f \x01(\tH\n" +
	"R\x11maxResolutionTier\x88\x01\x01\x126\n" +
	"\x15max_stored_frame_rate\x18\x10 \x01(\tH\vR\x12maxStoredFrameRate\x88\x01\x01\x12$\n" +
	"\vingest_type\x18\x11 \x01(\tH\fR\n" +
	"ingestType\x88\x01\x01\x12%\n" +
	"\vpassthrough\x18\x12 \x01(\tH\rR\vpassthrough\x88\x01\x01\x12\x1e\n" +
	"\bowner_id\x18\x13 \x01(\tH\x0eR\aownerId\x88\x01\x01\x12\"\n" +
	"\n" +
	"owner_type\x18\x14 \x01(\tH\x0fR\townerType\x88\x01\x01B\r\n" +
	"\v_deleted_atB\x10\n" +
	"\x0e_mux_upload_idB\x0f\n" +
	"\r_mux_asset_idB\x12\n" +
	"\x10_mux_playback_idB\t\n" +
	"\a_statusB\v\n" +
	"\t_durationB\x0f\n" +
	"\r_aspect_ratioB\t\n" +
	"\a_heightB\b\n" +
	"\x06_widthB\x13\n" +
	"\x11_asset_created_atB\x16\n" +
	"\x14_max_resolution_tierB\x18\n" +
	"\x16_max_stored_frame_rateB\x0e\n" +
	"\f_ingest_typeB\x0e\n" +
	"\f_passthroughB\v\n" +
	"\t_owner_idB\r\n" +
	"\v_owner_type\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\vGetResponse\x12%\n" +
	"\x05asset\x18\x01 \x01(\v2\x0f.asset.v0.AssetR\x05asset\"'\n" +
	"\x15GetWithDeletedRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x16GetWithDeletedResponse\x12%\n" +
	"\x05asset\x18\x01 \x01(\v2\x0f.asset.v0.AssetR\x05asset\";\n" +
	"\vListRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"M\n" +
	"\fListResponse\x12'\n" +
	"\x06assets\x18\x01 \x03(\v2\x0f.asset.v0.AssetR\x06assets\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"B\n" +
	"\x12ListDeletedRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"T\n" +
	"\x13ListDeletedResponse\x12'\n" +
	"\x06assets\x18\x01 \x03(\v2\x0f.asset.v0.AssetR\x06assets\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"B\n" +
	"\x12ListUnownedRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"T\n" +
	"\x13ListUnownedResponse\x12'\n" +
	"\x06assets\x18\x01 \x03(\v2\x0f.asset.v0.AssetR\x06assets\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\" \n" +
	"\x0eDeleteResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"(\n" +
	"\x16DeletePermanentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\")\n" +
	"\x17DeletePermanentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\" \n" +
	"\x0eRestoreRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"!\n" +
	"\x0fRestoreResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"R\n" +
	"\x16CreateUploadUrlRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"owner_type\x18\x02 \x01(\tR\townerType\"\xae\x01\n" +
	"\x17CreateUploadUrlResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\bowner_id\x18\x02 \x01(\tH\x00R\aownerId\x88\x01\x01\x12\"\n" +
	"\n" +
	"owner_type\x18\x03 \x01(\tH\x01R\townerType\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\x04 \x01(\tH\x02R\x05state\x88\x01\x01B\v\n" +
	"\t_owner_idB\r\n" +
	"\v_owner_typeB\b\n" +
	"\x06_state2\xac\x05\n" +
	"\fAssetService\x124\n" +
	"\x03Get\x12\x14.asset.v0.GetRequest\x1a\x15.asset.v0.GetResponse\"\x00\x12U\n" +
	"\x0eGetWithDeleted\x12\x1f.asset.v0.GetWithDeletedRequest\x1a .asset.v0.GetWithDeletedResponse\"\x00\x12>\n" +
	"\x04List\x12\x15.asset.v0.ListRequest\x1a\x1d.asset.v0.ListDeletedResponse\"\x00\x12L\n" +
	"\vListDeleted\x12\x1c.asset.v0.ListDeletedRequest\x1a\x1d.asset.v0.ListDeletedResponse\"\x00\x12L\n" +
	"\vListUnowned\x12\x1c.asset.v0.ListUnownedRequest\x1a\x1d.asset.v0.ListUnownedResponse\"\x00\x12=\n" +
	"\x06Delete\x12\x17.asset.v0.DeleteRequest\x1a\x18.asset.v0.DeleteResponse\"\x00\x12X\n" +
	"\x0fDeletePermanent\x12 .asset.v0.DeletePermanentRequest\x1a!.asset.v0.DeletePermanentResponse\"\x00\x12@\n" +
	"\aRestore\x12\x18.asset.v0.RestoreRequest\x1a\x19.asset.v0.RestoreResponse\"\x00\x12X\n" +
	"\x0fCreateUploadUrl\x12 .asset.v0.CreateUploadUrlRequest\x1a!.asset.v0.CreateUploadUrlResponse\"\x00BJZHgithub.com/mikhail5545/proto-go/proto/media_service/mux/asset/v0;assetpbb\x06proto3"

var (
	file_media_service_mux_asset_v0_asset_proto_rawDescOnce sync.Once
	file_media_service_mux_asset_v0_asset_proto_rawDescData []byte
)

func file_media_service_mux_asset_v0_asset_proto_rawDescGZIP() []byte {
	file_media_service_mux_asset_v0_asset_proto_rawDescOnce.Do(func() {
		file_media_service_mux_asset_v0_asset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_service_mux_asset_v0_asset_proto_rawDesc), len(file_media_service_mux_asset_v0_asset_proto_rawDesc)))
	})
	return file_media_service_mux_asset_v0_asset_proto_rawDescData
}

var file_media_service_mux_asset_v0_asset_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_media_service_mux_asset_v0_asset_proto_goTypes = []any{
	(*Asset)(nil),                   // 0: asset.v0.Asset
	(*GetRequest)(nil),              // 1: asset.v0.GetRequest
	(*GetResponse)(nil),             // 2: asset.v0.GetResponse
	(*GetWithDeletedRequest)(nil),   // 3: asset.v0.GetWithDeletedRequest
	(*GetWithDeletedResponse)(nil),  // 4: asset.v0.GetWithDeletedResponse
	(*ListRequest)(nil),             // 5: asset.v0.ListRequest
	(*ListResponse)(nil),            // 6: asset.v0.ListResponse
	(*ListDeletedRequest)(nil),      // 7: asset.v0.ListDeletedRequest
	(*ListDeletedResponse)(nil),     // 8: asset.v0.ListDeletedResponse
	(*ListUnownedRequest)(nil),      // 9: asset.v0.ListUnownedRequest
	(*ListUnownedResponse)(nil),     // 10: asset.v0.ListUnownedResponse
	(*DeleteRequest)(nil),           // 11: asset.v0.DeleteRequest
	(*DeleteResponse)(nil),          // 12: asset.v0.DeleteResponse
	(*DeletePermanentRequest)(nil),  // 13: asset.v0.DeletePermanentRequest
	(*DeletePermanentResponse)(nil), // 14: asset.v0.DeletePermanentResponse
	(*RestoreRequest)(nil),          // 15: asset.v0.RestoreRequest
	(*RestoreResponse)(nil),         // 16: asset.v0.RestoreResponse
	(*CreateUploadUrlRequest)(nil),  // 17: asset.v0.CreateUploadUrlRequest
	(*CreateUploadUrlResponse)(nil), // 18: asset.v0.CreateUploadUrlResponse
	(*timestamppb.Timestamp)(nil),   // 19: google.protobuf.Timestamp
}
var file_media_service_mux_asset_v0_asset_proto_depIdxs = []int32{
	19, // 0: asset.v0.Asset.created_at:type_name -> google.protobuf.Timestamp
	19, // 1: asset.v0.Asset.updated_at:type_name -> google.protobuf.Timestamp
	19, // 2: asset.v0.Asset.deleted_at:type_name -> google.protobuf.Timestamp
	19, // 3: asset.v0.Asset.asset_created_at:type_name -> google.protobuf.Timestamp
	0,  // 4: asset.v0.GetResponse.asset:type_name -> asset.v0.Asset
	0,  // 5: asset.v0.GetWithDeletedResponse.asset:type_name -> asset.v0.Asset
	0,  // 6: asset.v0.ListResponse.assets:type_name -> asset.v0.Asset
	0,  // 7: asset.v0.ListDeletedResponse.assets:type_name -> asset.v0.Asset
	0,  // 8: asset.v0.ListUnownedResponse.assets:type_name -> asset.v0.Asset
	1,  // 9: asset.v0.AssetService.Get:input_type -> asset.v0.GetRequest
	3,  // 10: asset.v0.AssetService.GetWithDeleted:input_type -> asset.v0.GetWithDeletedRequest
	5,  // 11: asset.v0.AssetService.List:input_type -> asset.v0.ListRequest
	7,  // 12: asset.v0.AssetService.ListDeleted:input_type -> asset.v0.ListDeletedRequest
	9,  // 13: asset.v0.AssetService.ListUnowned:input_type -> asset.v0.ListUnownedRequest
	11, // 14: asset.v0.AssetService.Delete:input_type -> asset.v0.DeleteRequest
	13, // 15: asset.v0.AssetService.DeletePermanent:input_type -> asset.v0.DeletePermanentRequest
	15, // 16: asset.v0.AssetService.Restore:input_type -> asset.v0.RestoreRequest
	17, // 17: asset.v0.AssetService.CreateUploadUrl:input_type -> asset.v0.CreateUploadUrlRequest
	2,  // 18: asset.v0.AssetService.Get:output_type -> asset.v0.GetResponse
	4,  // 19: asset.v0.AssetService.GetWithDeleted:output_type -> asset.v0.GetWithDeletedResponse
	8,  // 20: asset.v0.AssetService.List:output_type -> asset.v0.ListDeletedResponse
	8,  // 21: asset.v0.AssetService.ListDeleted:output_type -> asset.v0.ListDeletedResponse
	10, // 22: asset.v0.AssetService.ListUnowned:output_type -> asset.v0.ListUnownedResponse
	12, // 23: asset.v0.AssetService.Delete:output_type -> asset.v0.DeleteResponse
	14, // 24: asset.v0.AssetService.DeletePermanent:output_type -> asset.v0.DeletePermanentResponse
	16, // 25: asset.v0.AssetService.Restore:output_type -> asset.v0.RestoreResponse
	18, // 26: asset.v0.AssetService.CreateUploadUrl:output_type -> asset.v0.CreateUploadUrlResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_media_service_mux_asset_v0_asset_proto_init() }
func file_media_service_mux_asset_v0_asset_proto_init() {
	if File_media_service_mux_asset_v0_asset_proto != nil {
		return
	}
	file_media_service_mux_asset_v0_asset_proto_msgTypes[0].OneofWrappers = []any{}
	file_media_service_mux_asset_v0_asset_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_service_mux_asset_v0_asset_proto_rawDesc), len(file_media_service_mux_asset_v0_asset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_media_service_mux_asset_v0_asset_proto_goTypes,
		DependencyIndexes: file_media_service_mux_asset_v0_asset_proto_depIdxs,
		MessageInfos:      file_media_service_mux_asset_v0_asset_proto_msgTypes,
	}.Build()
	File_media_service_mux_asset_v0_asset_proto = out.File
	file_media_service_mux_asset_v0_asset_proto_goTypes = nil
	file_media_service_mux_asset_v0_asset_proto_depIdxs = nil
}
