/*
 * github.com/mikhail5545/proto-go
 * Copyright (c) 2026.  Mikhail Kulik
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: product_service/lesson/v0/lesson.proto

package lessonpb

import (
	v01 "github.com/mikhail5545/proto-go/proto/product_service/digital/v0"
	v0 "github.com/mikhail5545/proto-go/proto/product_service/lesson/lesson_video/v0"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LessonStatus int32

const (
	LessonStatus_STATUS_ACTIVE   LessonStatus = 0
	LessonStatus_STATUS_DRAFT    LessonStatus = 1
	LessonStatus_STATUS_ARCHIVED LessonStatus = 2
)

// Enum value maps for LessonStatus.
var (
	LessonStatus_name = map[int32]string{
		0: "STATUS_ACTIVE",
		1: "STATUS_DRAFT",
		2: "STATUS_ARCHIVED",
	}
	LessonStatus_value = map[string]int32{
		"STATUS_ACTIVE":   0,
		"STATUS_DRAFT":    1,
		"STATUS_ARCHIVED": 2,
	}
)

func (x LessonStatus) Enum() *LessonStatus {
	p := new(LessonStatus)
	*p = x
	return p
}

func (x LessonStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LessonStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_product_service_lesson_v0_lesson_proto_enumTypes[0].Descriptor()
}

func (LessonStatus) Type() protoreflect.EnumType {
	return &file_product_service_lesson_v0_lesson_proto_enumTypes[0]
}

func (x LessonStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LessonStatus.Descriptor instead.
func (LessonStatus) EnumDescriptor() ([]byte, []int) {
	return file_product_service_lesson_v0_lesson_proto_rawDescGZIP(), []int{0}
}

type Lesson struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	VariantUuid   []byte                 `protobuf:"bytes,5,opt,name=variant_uuid,json=variantUuid,proto3" json:"variant_uuid,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Slug          string                 `protobuf:"bytes,7,opt,name=slug,proto3" json:"slug,omitempty"`
	Position      int32                  `protobuf:"varint,8,opt,name=position,proto3" json:"position,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	IsPreview     bool                   `protobuf:"varint,10,opt,name=is_preview,json=isPreview,proto3" json:"is_preview,omitempty"`
	Status        LessonStatus           `protobuf:"varint,11,opt,name=status,proto3,enum=lesson.v0.LessonStatus" json:"status,omitempty"`
	IsExtra       bool                   `protobuf:"varint,12,opt,name=is_extra,json=isExtra,proto3" json:"is_extra,omitempty"`
	Note          *string                `protobuf:"bytes,13,opt,name=note,proto3,oneof" json:"note,omitempty"`
	ArchiveReason *string                `protobuf:"bytes,14,opt,name=archive_reason,json=archiveReason,proto3,oneof" json:"archive_reason,omitempty"`
	// Admin UUIDs
	CreatedBy   []byte `protobuf:"bytes,15,opt,name=created_by,json=createdBy,proto3,oneof" json:"created_by,omitempty"`
	PublishedBy []byte `protobuf:"bytes,16,opt,name=published_by,json=publishedBy,proto3,oneof" json:"published_by,omitempty"`
	ArchivedBy  []byte `protobuf:"bytes,17,opt,name=archived_by,json=archivedBy,proto3,oneof" json:"archived_by,omitempty"`
	RestoredBy  []byte `protobuf:"bytes,18,opt,name=restored_by,json=restoredBy,proto3,oneof" json:"restored_by,omitempty"`
	// Denormalized Admin Names for quick access
	CreatedByName   *string                  `protobuf:"bytes,19,opt,name=created_by_name,json=createdByName,proto3,oneof" json:"created_by_name,omitempty"`
	PublishedByName *string                  `protobuf:"bytes,20,opt,name=published_by_name,json=publishedByName,proto3,oneof" json:"published_by_name,omitempty"`
	ArchivedByName  *string                  `protobuf:"bytes,21,opt,name=archived_by_name,json=archivedByName,proto3,oneof" json:"archived_by_name,omitempty"`
	RestoredByName  *string                  `protobuf:"bytes,22,opt,name=restored_by_name,json=restoredByName,proto3,oneof" json:"restored_by_name,omitempty"`
	LatestVideoUuid []byte                   `protobuf:"bytes,23,opt,name=latest_video_uuid,json=latestVideoUuid,proto3,oneof" json:"latest_video_uuid,omitempty"`
	LatestVideo     *v0.LessonVideoVersion   `protobuf:"bytes,24,opt,name=latest_video,json=latestVideo,proto3,oneof" json:"latest_video,omitempty"`
	VideoVersions   []*v0.LessonVideoVersion `protobuf:"bytes,25,rep,name=video_versions,json=videoVersions,proto3" json:"video_versions,omitempty"`
	Attachments     []*v01.Asset             `protobuf:"bytes,26,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Lesson) Reset() {
	*x = Lesson{}
	mi := &file_product_service_lesson_v0_lesson_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lesson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lesson) ProtoMessage() {}

func (x *Lesson) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_lesson_v0_lesson_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lesson.ProtoReflect.Descriptor instead.
func (*Lesson) Descriptor() ([]byte, []int) {
	return file_product_service_lesson_v0_lesson_proto_rawDescGZIP(), []int{0}
}

func (x *Lesson) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Lesson) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Lesson) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Lesson) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Lesson) GetVariantUuid() []byte {
	if x != nil {
		return x.VariantUuid
	}
	return nil
}

func (x *Lesson) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Lesson) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Lesson) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Lesson) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Lesson) GetIsPreview() bool {
	if x != nil {
		return x.IsPreview
	}
	return false
}

func (x *Lesson) GetStatus() LessonStatus {
	if x != nil {
		return x.Status
	}
	return LessonStatus_STATUS_ACTIVE
}

func (x *Lesson) GetIsExtra() bool {
	if x != nil {
		return x.IsExtra
	}
	return false
}

func (x *Lesson) GetNote() string {
	if x != nil && x.Note != nil {
		return *x.Note
	}
	return ""
}

func (x *Lesson) GetArchiveReason() string {
	if x != nil && x.ArchiveReason != nil {
		return *x.ArchiveReason
	}
	return ""
}

func (x *Lesson) GetCreatedBy() []byte {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *Lesson) GetPublishedBy() []byte {
	if x != nil {
		return x.PublishedBy
	}
	return nil
}

func (x *Lesson) GetArchivedBy() []byte {
	if x != nil {
		return x.ArchivedBy
	}
	return nil
}

func (x *Lesson) GetRestoredBy() []byte {
	if x != nil {
		return x.RestoredBy
	}
	return nil
}

func (x *Lesson) GetCreatedByName() string {
	if x != nil && x.CreatedByName != nil {
		return *x.CreatedByName
	}
	return ""
}

func (x *Lesson) GetPublishedByName() string {
	if x != nil && x.PublishedByName != nil {
		return *x.PublishedByName
	}
	return ""
}

func (x *Lesson) GetArchivedByName() string {
	if x != nil && x.ArchivedByName != nil {
		return *x.ArchivedByName
	}
	return ""
}

func (x *Lesson) GetRestoredByName() string {
	if x != nil && x.RestoredByName != nil {
		return *x.RestoredByName
	}
	return ""
}

func (x *Lesson) GetLatestVideoUuid() []byte {
	if x != nil {
		return x.LatestVideoUuid
	}
	return nil
}

func (x *Lesson) GetLatestVideo() *v0.LessonVideoVersion {
	if x != nil {
		return x.LatestVideo
	}
	return nil
}

func (x *Lesson) GetVideoVersions() []*v0.LessonVideoVersion {
	if x != nil {
		return x.VideoVersions
	}
	return nil
}

func (x *Lesson) GetAttachments() []*v01.Asset {
	if x != nil {
		return x.Attachments
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3,oneof" json:"uuid,omitempty"`
	Slug          *string                `protobuf:"bytes,2,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_product_service_lesson_v0_lesson_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_lesson_v0_lesson_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_product_service_lesson_v0_lesson_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *GetRequest) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lesson        *Lesson                `protobuf:"bytes,1,opt,name=lesson,proto3" json:"lesson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_product_service_lesson_v0_lesson_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_lesson_v0_lesson_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_product_service_lesson_v0_lesson_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetLesson() *Lesson {
	if x != nil {
		return x.Lesson
	}
	return nil
}

type ListRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Uuids             [][]byte               `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	VariantUuids      [][]byte               `protobuf:"bytes,2,rep,name=variant_uuids,json=variantUuids,proto3" json:"variant_uuids,omitempty"`
	Slugs             []string               `protobuf:"bytes,3,rep,name=slugs,proto3" json:"slugs,omitempty"`
	ProductUuids      [][]byte               `protobuf:"bytes,4,rep,name=product_uuids,json=productUuids,proto3" json:"product_uuids,omitempty"`
	VideoVersionUuids [][]byte               `protobuf:"bytes,5,rep,name=video_version_uuids,json=videoVersionUuids,proto3" json:"video_version_uuids,omitempty"`
	IsPreview         *bool                  `protobuf:"varint,6,opt,name=is_preview,json=isPreview,proto3,oneof" json:"is_preview,omitempty"`
	IsExtra           *bool                  `protobuf:"varint,7,opt,name=is_extra,json=isExtra,proto3,oneof" json:"is_extra,omitempty"`
	OrderBy           *string                `protobuf:"bytes,8,opt,name=order_by,json=orderBy,proto3,oneof" json:"order_by,omitempty"`
	OrderDir          *string                `protobuf:"bytes,9,opt,name=order_dir,json=orderDir,proto3,oneof" json:"order_dir,omitempty"`
	PageSize          int32                  `protobuf:"varint,10,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken         string                 `protobuf:"bytes,11,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_product_service_lesson_v0_lesson_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_lesson_v0_lesson_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_product_service_lesson_v0_lesson_proto_rawDescGZIP(), []int{3}
}

func (x *ListRequest) GetUuids() [][]byte {
	if x != nil {
		return x.Uuids
	}
	return nil
}

func (x *ListRequest) GetVariantUuids() [][]byte {
	if x != nil {
		return x.VariantUuids
	}
	return nil
}

func (x *ListRequest) GetSlugs() []string {
	if x != nil {
		return x.Slugs
	}
	return nil
}

func (x *ListRequest) GetProductUuids() [][]byte {
	if x != nil {
		return x.ProductUuids
	}
	return nil
}

func (x *ListRequest) GetVideoVersionUuids() [][]byte {
	if x != nil {
		return x.VideoVersionUuids
	}
	return nil
}

func (x *ListRequest) GetIsPreview() bool {
	if x != nil && x.IsPreview != nil {
		return *x.IsPreview
	}
	return false
}

func (x *ListRequest) GetIsExtra() bool {
	if x != nil && x.IsExtra != nil {
		return *x.IsExtra
	}
	return false
}

func (x *ListRequest) GetOrderBy() string {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return ""
}

func (x *ListRequest) GetOrderDir() string {
	if x != nil && x.OrderDir != nil {
		return *x.OrderDir
	}
	return ""
}

func (x *ListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lessons       []*Lesson              `protobuf:"bytes,1,rep,name=lessons,proto3" json:"lessons,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_product_service_lesson_v0_lesson_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_lesson_v0_lesson_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_product_service_lesson_v0_lesson_proto_rawDescGZIP(), []int{4}
}

func (x *ListResponse) GetLessons() []*Lesson {
	if x != nil {
		return x.Lessons
	}
	return nil
}

func (x *ListResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VariantUuid   []byte                 `protobuf:"bytes,1,opt,name=variant_uuid,json=variantUuid,proto3" json:"variant_uuid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Position      int32                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	IsPreview     bool                   `protobuf:"varint,5,opt,name=is_preview,json=isPreview,proto3" json:"is_preview,omitempty"`
	IsExtra       bool                   `protobuf:"varint,6,opt,name=is_extra,json=isExtra,proto3" json:"is_extra,omitempty"`
	AdminUuid     []byte                 `protobuf:"bytes,7,opt,name=admin_uuid,json=adminUuid,proto3" json:"admin_uuid,omitempty"`
	AdminName     string                 `protobuf:"bytes,8,opt,name=admin_name,json=adminName,proto3" json:"admin_name,omitempty"`
	Note          string                 `protobuf:"bytes,9,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_product_service_lesson_v0_lesson_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_lesson_v0_lesson_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_product_service_lesson_v0_lesson_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRequest) GetVariantUuid() []byte {
	if x != nil {
		return x.VariantUuid
	}
	return nil
}

func (x *CreateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *CreateRequest) GetIsPreview() bool {
	if x != nil {
		return x.IsPreview
	}
	return false
}

func (x *CreateRequest) GetIsExtra() bool {
	if x != nil {
		return x.IsExtra
	}
	return false
}

func (x *CreateRequest) GetAdminUuid() []byte {
	if x != nil {
		return x.AdminUuid
	}
	return nil
}

func (x *CreateRequest) GetAdminName() string {
	if x != nil {
		return x.AdminName
	}
	return ""
}

func (x *CreateRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lesson        *Lesson                `protobuf:"bytes,1,opt,name=lesson,proto3" json:"lesson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_product_service_lesson_v0_lesson_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_lesson_v0_lesson_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_product_service_lesson_v0_lesson_proto_rawDescGZIP(), []int{6}
}

func (x *CreateResponse) GetLesson() *Lesson {
	if x != nil {
		return x.Lesson
	}
	return nil
}

type UpdateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Uuid           []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	VariantUuid    []byte                 `protobuf:"bytes,2,opt,name=variant_uuid,json=variantUuid,proto3" json:"variant_uuid,omitempty"`
	Title          *string                `protobuf:"bytes,3,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Slug           *string                `protobuf:"bytes,4,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	RegenerateSlug bool                   `protobuf:"varint,5,opt,name=regenerate_slug,json=regenerateSlug,proto3" json:"regenerate_slug,omitempty"`
	Position       *int32                 `protobuf:"varint,6,opt,name=position,proto3,oneof" json:"position,omitempty"`
	Description    *string                `protobuf:"bytes,7,opt,name=description,proto3,oneof" json:"description,omitempty"`
	IsPreview      *bool                  `protobuf:"varint,8,opt,name=is_preview,json=isPreview,proto3,oneof" json:"is_preview,omitempty"`
	IsExtra        *bool                  `protobuf:"varint,9,opt,name=is_extra,json=isExtra,proto3,oneof" json:"is_extra,omitempty"`
	Updates        *fieldmaskpb.FieldMask `protobuf:"bytes,10,opt,name=updates,proto3,oneof" json:"updates,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_product_service_lesson_v0_lesson_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_lesson_v0_lesson_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_product_service_lesson_v0_lesson_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *UpdateRequest) GetVariantUuid() []byte {
	if x != nil {
		return x.VariantUuid
	}
	return nil
}

func (x *UpdateRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateRequest) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

func (x *UpdateRequest) GetRegenerateSlug() bool {
	if x != nil {
		return x.RegenerateSlug
	}
	return false
}

func (x *UpdateRequest) GetPosition() int32 {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return 0
}

func (x *UpdateRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateRequest) GetIsPreview() bool {
	if x != nil && x.IsPreview != nil {
		return *x.IsPreview
	}
	return false
}

func (x *UpdateRequest) GetIsExtra() bool {
	if x != nil && x.IsExtra != nil {
		return *x.IsExtra
	}
	return false
}

func (x *UpdateRequest) GetUpdates() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Updates
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Slug          *string                `protobuf:"bytes,3,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	Position      *int32                 `protobuf:"varint,4,opt,name=position,proto3,oneof" json:"position,omitempty"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	IsPreview     *bool                  `protobuf:"varint,6,opt,name=is_preview,json=isPreview,proto3,oneof" json:"is_preview,omitempty"`
	IsExtra       *bool                  `protobuf:"varint,7,opt,name=is_extra,json=isExtra,proto3,oneof" json:"is_extra,omitempty"`
	Updates       *fieldmaskpb.FieldMask `protobuf:"bytes,8,opt,name=updates,proto3,oneof" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_product_service_lesson_v0_lesson_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_lesson_v0_lesson_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_product_service_lesson_v0_lesson_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateResponse) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *UpdateResponse) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateResponse) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

func (x *UpdateResponse) GetPosition() int32 {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return 0
}

func (x *UpdateResponse) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateResponse) GetIsPreview() bool {
	if x != nil && x.IsPreview != nil {
		return *x.IsPreview
	}
	return false
}

func (x *UpdateResponse) GetIsExtra() bool {
	if x != nil && x.IsExtra != nil {
		return *x.IsExtra
	}
	return false
}

func (x *UpdateResponse) GetUpdates() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Updates
	}
	return nil
}

type ChangeStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Note          *string                `protobuf:"bytes,2,opt,name=note,proto3,oneof" json:"note,omitempty"`
	AdminUuid     []byte                 `protobuf:"bytes,3,opt,name=admin_uuid,json=adminUuid,proto3" json:"admin_uuid,omitempty"`
	AdminName     string                 `protobuf:"bytes,4,opt,name=admin_name,json=adminName,proto3" json:"admin_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeStateRequest) Reset() {
	*x = ChangeStateRequest{}
	mi := &file_product_service_lesson_v0_lesson_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeStateRequest) ProtoMessage() {}

func (x *ChangeStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_lesson_v0_lesson_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeStateRequest.ProtoReflect.Descriptor instead.
func (*ChangeStateRequest) Descriptor() ([]byte, []int) {
	return file_product_service_lesson_v0_lesson_proto_rawDescGZIP(), []int{9}
}

func (x *ChangeStateRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *ChangeStateRequest) GetNote() string {
	if x != nil && x.Note != nil {
		return *x.Note
	}
	return ""
}

func (x *ChangeStateRequest) GetAdminUuid() []byte {
	if x != nil {
		return x.AdminUuid
	}
	return nil
}

func (x *ChangeStateRequest) GetAdminName() string {
	if x != nil {
		return x.AdminName
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_product_service_lesson_v0_lesson_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_lesson_v0_lesson_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_product_service_lesson_v0_lesson_proto_rawDescGZIP(), []int{10}
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_product_service_lesson_v0_lesson_proto protoreflect.FileDescriptor

const file_product_service_lesson_v0_lesson_proto_rawDesc = "" +
	"\n" +
	"&product_service/lesson/v0/lesson.proto\x12\tlesson.v0\x1a9product_service/lesson/lesson_video/v0/lesson_video.proto\x1a(product_service/digital/v0/digital.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xc6\n" +
	"\n" +
	"\x06Lesson\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tdeletedAt\x88\x01\x01\x12!\n" +
	"\fvariant_uuid\x18\x05 \x01(\fR\vvariantUuid\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\a \x01(\tR\x04slug\x12\x1a\n" +
	"\bposition\x18\b \x01(\x05R\bposition\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"is_preview\x18\n" +
	" \x01(\bR\tisPreview\x12/\n" +
	"\x06status\x18\v \x01(\x0e2\x17.lesson.v0.LessonStatusR\x06status\x12\x19\n" +
	"\bis_extra\x18\f \x01(\bR\aisExtra\x12\x17\n" +
	"\x04note\x18\r \x01(\tH\x01R\x04note\x88\x01\x01\x12*\n" +
	"\x0earchive_reason\x18\x0e \x01(\tH\x02R\rarchiveReason\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_by\x18\x0f \x01(\fH\x03R\tcreatedBy\x88\x01\x01\x12&\n" +
	"\fpublished_by\x18\x10 \x01(\fH\x04R\vpublishedBy\x88\x01\x01\x12$\n" +
	"\varchived_by\x18\x11 \x01(\fH\x05R\n" +
	"archivedBy\x88\x01\x01\x12$\n" +
	"\vrestored_by\x18\x12 \x01(\fH\x06R\n" +
	"restoredBy\x88\x01\x01\x12+\n" +
	"\x0fcreated_by_name\x18\x13 \x01(\tH\aR\rcreatedByName\x88\x01\x01\x12/\n" +
	"\x11published_by_name\x18\x14 \x01(\tH\bR\x0fpublishedByName\x88\x01\x01\x12-\n" +
	"\x10archived_by_name\x18\x15 \x01(\tH\tR\x0earchivedByName\x88\x01\x01\x12-\n" +
	"\x10restored_by_name\x18\x16 \x01(\tH\n" +
	"R\x0erestoredByName\x88\x01\x01\x12/\n" +
	"\x11latest_video_uuid\x18\x17 \x01(\fH\vR\x0flatestVideoUuid\x88\x01\x01\x12K\n" +
	"\flatest_video\x18\x18 \x01(\v2#.lesson_video.v0.LessonVideoVersionH\fR\vlatestVideo\x88\x01\x01\x12J\n" +
	"\x0evideo_versions\x18\x19 \x03(\v2#.lesson_video.v0.LessonVideoVersionR\rvideoVersions\x123\n" +
	"\vattachments\x18\x1a \x03(\v2\x11.digital.v0.AssetR\vattachmentsB\r\n" +
	"\v_deleted_atB\a\n" +
	"\x05_noteB\x11\n" +
	"\x0f_archive_reasonB\r\n" +
	"\v_created_byB\x0f\n" +
	"\r_published_byB\x0e\n" +
	"\f_archived_byB\x0e\n" +
	"\f_restored_byB\x12\n" +
	"\x10_created_by_nameB\x14\n" +
	"\x12_published_by_nameB\x13\n" +
	"\x11_archived_by_nameB\x13\n" +
	"\x11_restored_by_nameB\x14\n" +
	"\x12_latest_video_uuidB\x0f\n" +
	"\r_latest_video\"P\n" +
	"\n" +
	"GetRequest\x12\x17\n" +
	"\x04uuid\x18\x01 \x01(\fH\x00R\x04uuid\x88\x01\x01\x12\x17\n" +
	"\x04slug\x18\x02 \x01(\tH\x01R\x04slug\x88\x01\x01B\a\n" +
	"\x05_uuidB\a\n" +
	"\x05_slug\"8\n" +
	"\vGetResponse\x12)\n" +
	"\x06lesson\x18\x01 \x01(\v2\x11.lesson.v0.LessonR\x06lesson\"\xac\x03\n" +
	"\vListRequest\x12\x14\n" +
	"\x05uuids\x18\x01 \x03(\fR\x05uuids\x12#\n" +
	"\rvariant_uuids\x18\x02 \x03(\fR\fvariantUuids\x12\x14\n" +
	"\x05slugs\x18\x03 \x03(\tR\x05slugs\x12#\n" +
	"\rproduct_uuids\x18\x04 \x03(\fR\fproductUuids\x12.\n" +
	"\x13video_version_uuids\x18\x05 \x03(\fR\x11videoVersionUuids\x12\"\n" +
	"\n" +
	"is_preview\x18\x06 \x01(\bH\x00R\tisPreview\x88\x01\x01\x12\x1e\n" +
	"\bis_extra\x18\a \x01(\bH\x01R\aisExtra\x88\x01\x01\x12\x1e\n" +
	"\border_by\x18\b \x01(\tH\x02R\aorderBy\x88\x01\x01\x12 \n" +
	"\torder_dir\x18\t \x01(\tH\x03R\borderDir\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\n" +
	" \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\v \x01(\tR\tpageTokenB\r\n" +
	"\v_is_previewB\v\n" +
	"\t_is_extraB\v\n" +
	"\t_order_byB\f\n" +
	"\n" +
	"_order_dir\"c\n" +
	"\fListResponse\x12+\n" +
	"\alessons\x18\x01 \x03(\v2\x11.lesson.v0.LessonR\alessons\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x84\x02\n" +
	"\rCreateRequest\x12!\n" +
	"\fvariant_uuid\x18\x01 \x01(\fR\vvariantUuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x05R\bposition\x12\x1d\n" +
	"\n" +
	"is_preview\x18\x05 \x01(\bR\tisPreview\x12\x19\n" +
	"\bis_extra\x18\x06 \x01(\bR\aisExtra\x12\x1d\n" +
	"\n" +
	"admin_uuid\x18\a \x01(\fR\tadminUuid\x12\x1d\n" +
	"\n" +
	"admin_name\x18\b \x01(\tR\tadminName\x12\x12\n" +
	"\x04note\x18\t \x01(\tR\x04note\";\n" +
	"\x0eCreateResponse\x12)\n" +
	"\x06lesson\x18\x01 \x01(\v2\x11.lesson.v0.LessonR\x06lesson\"\xc2\x03\n" +
	"\rUpdateRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x12!\n" +
	"\fvariant_uuid\x18\x02 \x01(\fR\vvariantUuid\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x17\n" +
	"\x04slug\x18\x04 \x01(\tH\x01R\x04slug\x88\x01\x01\x12'\n" +
	"\x0fregenerate_slug\x18\x05 \x01(\bR\x0eregenerateSlug\x12\x1f\n" +
	"\bposition\x18\x06 \x01(\x05H\x02R\bposition\x88\x01\x01\x12%\n" +
	"\vdescription\x18\a \x01(\tH\x03R\vdescription\x88\x01\x01\x12\"\n" +
	"\n" +
	"is_preview\x18\b \x01(\bH\x04R\tisPreview\x88\x01\x01\x12\x1e\n" +
	"\bis_extra\x18\t \x01(\bH\x05R\aisExtra\x88\x01\x01\x129\n" +
	"\aupdates\x18\n" +
	" \x01(\v2\x1a.google.protobuf.FieldMaskH\x06R\aupdates\x88\x01\x01B\b\n" +
	"\x06_titleB\a\n" +
	"\x05_slugB\v\n" +
	"\t_positionB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_is_previewB\v\n" +
	"\t_is_extraB\n" +
	"\n" +
	"\b_updates\"\xf7\x02\n" +
	"\x0eUpdateResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x17\n" +
	"\x04slug\x18\x03 \x01(\tH\x01R\x04slug\x88\x01\x01\x12\x1f\n" +
	"\bposition\x18\x04 \x01(\x05H\x02R\bposition\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x03R\vdescription\x88\x01\x01\x12\"\n" +
	"\n" +
	"is_preview\x18\x06 \x01(\bH\x04R\tisPreview\x88\x01\x01\x12\x1e\n" +
	"\bis_extra\x18\a \x01(\bH\x05R\aisExtra\x88\x01\x01\x129\n" +
	"\aupdates\x18\b \x01(\v2\x1a.google.protobuf.FieldMaskH\x06R\aupdates\x88\x01\x01B\b\n" +
	"\x06_titleB\a\n" +
	"\x05_slugB\v\n" +
	"\t_positionB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_is_previewB\v\n" +
	"\t_is_extraB\n" +
	"\n" +
	"\b_updates\"\x88\x01\n" +
	"\x12ChangeStateRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x12\x17\n" +
	"\x04note\x18\x02 \x01(\tH\x00R\x04note\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"admin_uuid\x18\x03 \x01(\fR\tadminUuid\x12\x1d\n" +
	"\n" +
	"admin_name\x18\x04 \x01(\tR\tadminNameB\a\n" +
	"\x05_note\",\n" +
	"\fPingResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp*H\n" +
	"\fLessonStatus\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x00\x12\x10\n" +
	"\fSTATUS_DRAFT\x10\x01\x12\x13\n" +
	"\x0fSTATUS_ARCHIVED\x10\x022\xfc\x05\n" +
	"\rLessonService\x127\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x17.lesson.v0.PingResponse\x124\n" +
	"\x03Get\x12\x15.lesson.v0.GetRequest\x1a\x16.lesson.v0.GetResponse\x12=\n" +
	"\fGetWithDraft\x12\x15.lesson.v0.GetRequest\x1a\x16.lesson.v0.GetResponse\x12@\n" +
	"\x0fGetWithArchived\x12\x15.lesson.v0.GetRequest\x1a\x16.lesson.v0.GetResponse\x127\n" +
	"\x04List\x12\x16.lesson.v0.ListRequest\x1a\x17.lesson.v0.ListResponse\x12=\n" +
	"\n" +
	"ListDrafts\x12\x16.lesson.v0.ListRequest\x1a\x17.lesson.v0.ListResponse\x12?\n" +
	"\fListArchived\x12\x16.lesson.v0.ListRequest\x1a\x17.lesson.v0.ListResponse\x12=\n" +
	"\x06Create\x12\x18.lesson.v0.CreateRequest\x1a\x19.lesson.v0.CreateResponse\x12=\n" +
	"\x06Update\x12\x18.lesson.v0.UpdateRequest\x1a\x19.lesson.v0.UpdateResponse\x12@\n" +
	"\aPublish\x12\x1d.lesson.v0.ChangeStateRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\aArchive\x12\x1d.lesson.v0.ChangeStateRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\aRestore\x12\x1d.lesson.v0.ChangeStateRequest\x1a\x16.google.protobuf.EmptyBJZHgithub.com/mikhail5545/proto-go/proto/product_service/lesson/v0;lessonpbb\x06proto3"

var (
	file_product_service_lesson_v0_lesson_proto_rawDescOnce sync.Once
	file_product_service_lesson_v0_lesson_proto_rawDescData []byte
)

func file_product_service_lesson_v0_lesson_proto_rawDescGZIP() []byte {
	file_product_service_lesson_v0_lesson_proto_rawDescOnce.Do(func() {
		file_product_service_lesson_v0_lesson_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_service_lesson_v0_lesson_proto_rawDesc), len(file_product_service_lesson_v0_lesson_proto_rawDesc)))
	})
	return file_product_service_lesson_v0_lesson_proto_rawDescData
}

var file_product_service_lesson_v0_lesson_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_product_service_lesson_v0_lesson_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_product_service_lesson_v0_lesson_proto_goTypes = []any{
	(LessonStatus)(0),             // 0: lesson.v0.LessonStatus
	(*Lesson)(nil),                // 1: lesson.v0.Lesson
	(*GetRequest)(nil),            // 2: lesson.v0.GetRequest
	(*GetResponse)(nil),           // 3: lesson.v0.GetResponse
	(*ListRequest)(nil),           // 4: lesson.v0.ListRequest
	(*ListResponse)(nil),          // 5: lesson.v0.ListResponse
	(*CreateRequest)(nil),         // 6: lesson.v0.CreateRequest
	(*CreateResponse)(nil),        // 7: lesson.v0.CreateResponse
	(*UpdateRequest)(nil),         // 8: lesson.v0.UpdateRequest
	(*UpdateResponse)(nil),        // 9: lesson.v0.UpdateResponse
	(*ChangeStateRequest)(nil),    // 10: lesson.v0.ChangeStateRequest
	(*PingResponse)(nil),          // 11: lesson.v0.PingResponse
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*v0.LessonVideoVersion)(nil), // 13: lesson_video.v0.LessonVideoVersion
	(*v01.Asset)(nil),             // 14: digital.v0.Asset
	(*fieldmaskpb.FieldMask)(nil), // 15: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),         // 16: google.protobuf.Empty
}
var file_product_service_lesson_v0_lesson_proto_depIdxs = []int32{
	12, // 0: lesson.v0.Lesson.created_at:type_name -> google.protobuf.Timestamp
	12, // 1: lesson.v0.Lesson.updated_at:type_name -> google.protobuf.Timestamp
	12, // 2: lesson.v0.Lesson.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 3: lesson.v0.Lesson.status:type_name -> lesson.v0.LessonStatus
	13, // 4: lesson.v0.Lesson.latest_video:type_name -> lesson_video.v0.LessonVideoVersion
	13, // 5: lesson.v0.Lesson.video_versions:type_name -> lesson_video.v0.LessonVideoVersion
	14, // 6: lesson.v0.Lesson.attachments:type_name -> digital.v0.Asset
	1,  // 7: lesson.v0.GetResponse.lesson:type_name -> lesson.v0.Lesson
	1,  // 8: lesson.v0.ListResponse.lessons:type_name -> lesson.v0.Lesson
	1,  // 9: lesson.v0.CreateResponse.lesson:type_name -> lesson.v0.Lesson
	15, // 10: lesson.v0.UpdateRequest.updates:type_name -> google.protobuf.FieldMask
	15, // 11: lesson.v0.UpdateResponse.updates:type_name -> google.protobuf.FieldMask
	16, // 12: lesson.v0.LessonService.Ping:input_type -> google.protobuf.Empty
	2,  // 13: lesson.v0.LessonService.Get:input_type -> lesson.v0.GetRequest
	2,  // 14: lesson.v0.LessonService.GetWithDraft:input_type -> lesson.v0.GetRequest
	2,  // 15: lesson.v0.LessonService.GetWithArchived:input_type -> lesson.v0.GetRequest
	4,  // 16: lesson.v0.LessonService.List:input_type -> lesson.v0.ListRequest
	4,  // 17: lesson.v0.LessonService.ListDrafts:input_type -> lesson.v0.ListRequest
	4,  // 18: lesson.v0.LessonService.ListArchived:input_type -> lesson.v0.ListRequest
	6,  // 19: lesson.v0.LessonService.Create:input_type -> lesson.v0.CreateRequest
	8,  // 20: lesson.v0.LessonService.Update:input_type -> lesson.v0.UpdateRequest
	10, // 21: lesson.v0.LessonService.Publish:input_type -> lesson.v0.ChangeStateRequest
	10, // 22: lesson.v0.LessonService.Archive:input_type -> lesson.v0.ChangeStateRequest
	10, // 23: lesson.v0.LessonService.Restore:input_type -> lesson.v0.ChangeStateRequest
	11, // 24: lesson.v0.LessonService.Ping:output_type -> lesson.v0.PingResponse
	3,  // 25: lesson.v0.LessonService.Get:output_type -> lesson.v0.GetResponse
	3,  // 26: lesson.v0.LessonService.GetWithDraft:output_type -> lesson.v0.GetResponse
	3,  // 27: lesson.v0.LessonService.GetWithArchived:output_type -> lesson.v0.GetResponse
	5,  // 28: lesson.v0.LessonService.List:output_type -> lesson.v0.ListResponse
	5,  // 29: lesson.v0.LessonService.ListDrafts:output_type -> lesson.v0.ListResponse
	5,  // 30: lesson.v0.LessonService.ListArchived:output_type -> lesson.v0.ListResponse
	7,  // 31: lesson.v0.LessonService.Create:output_type -> lesson.v0.CreateResponse
	9,  // 32: lesson.v0.LessonService.Update:output_type -> lesson.v0.UpdateResponse
	16, // 33: lesson.v0.LessonService.Publish:output_type -> google.protobuf.Empty
	16, // 34: lesson.v0.LessonService.Archive:output_type -> google.protobuf.Empty
	16, // 35: lesson.v0.LessonService.Restore:output_type -> google.protobuf.Empty
	24, // [24:36] is the sub-list for method output_type
	12, // [12:24] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_product_service_lesson_v0_lesson_proto_init() }
func file_product_service_lesson_v0_lesson_proto_init() {
	if File_product_service_lesson_v0_lesson_proto != nil {
		return
	}
	file_product_service_lesson_v0_lesson_proto_msgTypes[0].OneofWrappers = []any{}
	file_product_service_lesson_v0_lesson_proto_msgTypes[1].OneofWrappers = []any{}
	file_product_service_lesson_v0_lesson_proto_msgTypes[3].OneofWrappers = []any{}
	file_product_service_lesson_v0_lesson_proto_msgTypes[7].OneofWrappers = []any{}
	file_product_service_lesson_v0_lesson_proto_msgTypes[8].OneofWrappers = []any{}
	file_product_service_lesson_v0_lesson_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_service_lesson_v0_lesson_proto_rawDesc), len(file_product_service_lesson_v0_lesson_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_service_lesson_v0_lesson_proto_goTypes,
		DependencyIndexes: file_product_service_lesson_v0_lesson_proto_depIdxs,
		EnumInfos:         file_product_service_lesson_v0_lesson_proto_enumTypes,
		MessageInfos:      file_product_service_lesson_v0_lesson_proto_msgTypes,
	}.Build()
	File_product_service_lesson_v0_lesson_proto = out.File
	file_product_service_lesson_v0_lesson_proto_goTypes = nil
	file_product_service_lesson_v0_lesson_proto_depIdxs = nil
}
